/**
 * AuthService — Firebase Authentication + BrincaBytes SSO
 *
 * OOP Paradigms:
 * - Encapsulation: private firebase instances
 * - Single Responsibility: only auth logic
 */
import { Player } from '../entities/Player.js';
import EventBus from '../core/EventBus.js';

class AuthService {
    #auth;   // Firebase Auth instance
    #player; // Guest player by default
    #unsubscribe;
    #isBrincaBytesUser = false;

    constructor() {
        this.#auth = null;
        this.#player = new Player();
        this.#unsubscribe = null;
    }

    /**
     * Initialize with Firebase Auth instance.
     * Call this once from app.js after Firebase is initialized.
     */
    init(firebaseAuth) {
        this.#auth = firebaseAuth;

        // Listen for auth state changes
        this.#unsubscribe = firebaseAuth.onAuthStateChanged(async user => {
            // Ignore Firebase native logout events if we are running hybrid BrincaBytes SSO
            if (this.#isBrincaBytesUser) return;

            if (user) {
                this.#player.setProfile({
                    uid: user.uid,
                    nome: user.displayName || user.email?.split('@')[0] || 'Programador',
                    email: user.email || '',
                    avatar: user.photoURL || this.#getInitialsAvatar(user.displayName || 'P'),
                });
                EventBus.emit('auth:loggedIn', { player: this.#player.toPublic() });
            } else {
                this.#player = this.#loadGuestPlayer();
                EventBus.emit('auth:loggedOut', {});
            }
        });

        // Listen for iframe postMessage from BrincaBytes SSO
        window.addEventListener('message', (event) => {
            // Securely listens for the login payload sent via postMessage from the parent window
            if (event.data && event.data.type === 'BRINCABYTES_LOGIN') {
                const user = event.data.user;
                if (user && user.uid) {
                    this.#isBrincaBytesUser = true;

                    this.#player.setProfile({
                        uid: user.uid,
                        nome: user.nome || 'Programador',
                        email: user.email || '',
                        avatar: user.avatar || this.#getInitialsAvatar(user.nome || 'P'),
                    });

                    // We dispatch loggedIn, simulating a successful Firebase connection
                    // allowing ProgressService to save state under this specific BrincaBytes UID
                    EventBus.emit('auth:loggedIn', { player: this.#player.toPublic() });
                }
            }
        });
    }

    get player() { return this.#player; }
    get isAuthenticated() { return !this.#player.isGuest; }

    /** Login with Google OAuth */
    async loginWithGoogle() {
        if (!this.#auth) return this.#offlineMode();
        try {
            const { GoogleAuthProvider, signInWithPopup } = await import('https://www.gstatic.com/firebasejs/10.12.0/firebase-auth.js');
            const provider = new GoogleAuthProvider();
            const result = await signInWithPopup(this.#auth, provider);
            return result.user;
        } catch (err) {
            console.error('[AuthService] Google login failed:', err);
            throw err;
        }
    }

    /** Login with email + password */
    async loginWithEmail(email, password) {
        if (!this.#auth) return this.#offlineMode();
        const { signInWithEmailAndPassword } = await import('https://www.gstatic.com/firebasejs/10.12.0/firebase-auth.js');
        return signInWithEmailAndPassword(this.#auth, email, password);
    }

    /**
     * BrincaBytes SSO — login with custom token generated by the portal.
     * The portal backend must create a Firebase custom token for the user.
     * @param {string} customToken — generated by BrincaBytes backend
     */
    async loginWithBrincaBytesToken(customToken) {
        if (!this.#auth) return this.#offlineMode();
        const { signInWithCustomToken } = await import('https://www.gstatic.com/firebasejs/10.12.0/firebase-auth.js');
        return signInWithCustomToken(this.#auth, customToken);
    }

    /** Logout */
    async logout() {
        if (this.#auth) {
            const { signOut } = await import('https://www.gstatic.com/firebasejs/10.12.0/firebase-auth.js');
            await signOut(this.#auth);
        }
        this.#player = this.#loadGuestPlayer();
        EventBus.emit('auth:loggedOut', {});
    }

    /** Guest player persisted with localStorage */
    #loadGuestPlayer() {
        const nome = localStorage.getItem('cc_nome') || '';
        return new Player({ nome, avatar: '👤' });
    }

    setGuestName(nome) {
        localStorage.setItem('cc_nome', nome);
        this.#player.setProfile({ nome });
    }

    #getInitialsAvatar(name) {
        return name.split(' ').map(w => w[0]).slice(0, 2).join('').toUpperCase();
    }

    #offlineMode() {
        console.warn('[AuthService] Firebase not configured — running offline.');
        return null;
    }

    destroy() {
        this.#unsubscribe?.();
    }
}

export default new AuthService();
