/* ════════════════════════════════════════════════════════
       LOJA: PETS E PODERES
    ════════════════════════════════════════════════════════ */
    const LOJA_PETS = [
      { id: 'robo', emoji: '🤖', nome: 'BYTE-BOT', desc: 'O robô original! Sempre pronto.', preco: 0, gratis: true },
      { id: 'gato', emoji: '🐱', nome: 'GATINHO', desc: 'Miau! Um gatinho esperto para apresentar.', preco: 30 },
      { id: 'cao', emoji: '🐶', nome: 'CACHORRÃO', desc: 'Leal e animado! Ama fazer as perguntas.', preco: 50 },
      { id: 'panda', emoji: '🐼', nome: 'PANDINHA', desc: 'Fofíssimo e superesperto!', preco: 70 },
      { id: 'dragao', emoji: '🐲', nome: 'DRAGÃOZINHO', desc: 'Mágico e corajoso! Sopra fogo nos erros.', preco: 100 },
      { id: 'unicorn', emoji: '🦄', nome: 'UNICÓRNIO', desc: 'Arco-íris e magia em cada resposta!', preco: 120 },
      { id: 'alien', emoji: '👾', nome: 'ALIENÍGENA', desc: 'Veio do espaço para aprender tudo!', preco: 150 },
      { id: 'dinossauro', emoji: '🦕', nome: 'DINOSSAURO', desc: 'O mais antigo amigo dos bytes!', preco: 180 },
    ];

    const LOJA_PODERES = [
      { id: 'vidas_extra', emoji: '❤️', nome: 'VIDAS EXTRA', desc: 'Começa cada trilha com +1 vida (4 no total)!', preco: 60, tipo: 'passivo' },
      { id: 'dica_mestre', emoji: '💡', nome: 'DICA ESPECIAL', desc: 'Elimina 1 opção errada por partida!', preco: 80, tipo: 'ativo', usos: 1 },
      { id: 'dobro_moedas', emoji: '💎', nome: 'DOBRO DE MOEDAS', desc: 'Ganha 20 BM por acerto em vez de 10!', preco: 100, tipo: 'passivo' },
      { id: 'segunda_chance', emoji: '🍀', nome: 'SEGUNDA CHANCE', desc: 'Em 1 erro por partida, não perde vida!', preco: 120, tipo: 'passivo' },
    ];

    /* ════════════════════════════════════════════════════════
       TRILHAS PRÉ-DEFINIDAS
    ════════════════════════════════════════════════════════ */
    const TRILHAS_FIXAS = [
      { id: 'port', nome: 'PORTUGUÊS', emoji: '📖', desc: 'Letras, palavras e histórias!', cor: '#ff79c6', corDk: '#7a0040', desbloqueio: 0 },
      { id: 'mat', nome: 'MATEMÁTICA', emoji: '🔢', desc: 'Números, contas e desafios!', cor: '#5bcbff', corDk: '#004a6e', desbloqueio: 0 },
      { id: 'ciencias', nome: 'CIÊNCIAS', emoji: '🔬', desc: 'Natureza, animais e o corpo humano!', cor: '#3ddc84', corDk: '#004a2e', desbloqueio: 0 },
      { id: 'historia', nome: 'HISTÓRIA', emoji: '🏛️', desc: 'O Brasil e o mundo que nos formaram!', cor: '#ffb347', corDk: '#6a3a00', desbloqueio: 0 },
      { id: 'geo', nome: 'GEOGRAFIA', emoji: '🌎', desc: 'Países, estados e o nosso planeta!', cor: '#00e5cc', corDk: '#007a6a', desbloqueio: 0 },
      { id: 'artes', nome: 'ARTES', emoji: '🎨', desc: 'Cores, músicas e criatividade!', cor: '#c084fc', corDk: '#5a0a9e', desbloqueio: 0 },
    ];

    /* ════════════════════════════════════════════════════════
       BANCO DE PERGUNTAS — ANOS INICIAIS (1º ao 5º ano)
    ════════════════════════════════════════════════════════ */
    const BANCO = {
      /* ── PORTUGUÊS ── */
      port: {
        niveis: [
          { nome: '⭐ LEITOR INICIANTE', inicio: 0, fala: 'Vamos explorar as palavras! Você é um leitor incrível!' },
          { nome: '⭐⭐ CONTADOR DE HISTÓRIAS', inicio: 5, fala: 'Nível 2! As palavras têm muito poder!' },
          { nome: '⭐⭐⭐ ESCRITOR CRIATIVO', inicio: 10, fala: 'Nível 3! Você está ficando ótimo no português!' },
          { nome: '💎 MESTRE DAS LETRAS', inicio: 15, fala: 'NÍVEL MESTRE! Você domina o Português!' },
        ],
        perguntas: [
          { tipo: 'multipla', pergunta: 'Quantas vogais tem o alfabeto português?', opcoes: ['3', '5', '7', '9'], correta: 1, reacao_acerto: 'As vogais são: A, E, I, O, U!', reacao_erro: 'São 5 vogais: A, E, I, O, U!', curiosidade: 'Vogais são sons abertos que saem direto da boca. Sem elas, não conseguimos falar quase nada! 🗣️' },
          { tipo: 'vf', pergunta: 'A letra "B" é uma vogal.', correta: false, reacao_acerto: 'Certo! B é consoante!', reacao_erro: 'Era FALSO! B é consoante, não vogal!', curiosidade: 'Consoantes precisam de uma vogal para formar sílabas. Tente falar só "B"... difícil né? 😄' },
          { tipo: 'multipla', pergunta: 'Qual palavra tem 3 sílabas?', opcoes: ['Sol', 'Casa', 'Borboleta', 'Flor'], correta: 2, reacao_acerto: 'Bor-bo-le-ta tem 4 sílabas!', reacao_erro: 'Borboleta tem 4 sílabas: Bor-bo-le-ta!', curiosidade: 'Contar sílabas é como bater palmas enquanto fala a palavra. Tente: Bor(palma)-bo(palma)-le(palma)-ta(palma)! 👏' },
          { tipo: 'completar', pergunta: 'A palavra que dá nome a uma pessoa, lugar ou coisa é o _____.', resposta: 'substantivo', dica: '(dica: sub_ _ _ _ _ ivo)', reacao_acerto: 'Substantivo! Que ótimo!', reacao_erro: 'Era SUBSTANTIVO!', curiosidade: 'Mesa, João, Brasil, amor — todos são substantivos! Eles são o nome das coisas do mundo. 📝' },
          { tipo: 'vf', pergunta: '"Feliz" é o contrário de "triste".', correta: true, reacao_acerto: 'Isso mesmo! São antônimos!', reacao_erro: 'Era VERDADEIRO! Feliz e triste são opostos!', curiosidade: 'Palavras com sentido oposto se chamam antônimos. Quente/frio, alto/baixo, rápido/lento! 🔁' },
          { tipo: 'multipla', pergunta: 'Qual é a forma correta?', opcoes: ['Os menino brinca', 'Os meninos brinCA', 'Os meninos brincam', 'O meninos brincam'], correta: 2, reacao_acerto: 'Concordância perfeita!', reacao_erro: 'A correta é "Os meninos brincam"!', curiosidade: 'Sujeito e verbo precisam combinar em número. Se há vários meninos, o verbo também precisa ser plural! 🎯' },
          { tipo: 'ordenar', pergunta: 'Coloque as partes do texto na ordem correta:', itens: ['Desenvolvimento', 'Conclusão', 'Introdução'], ordemCorreta: [2, 0, 1], reacao_acerto: 'Você sabe estruturar um texto!', reacao_erro: 'A ordem é: Introdução → Desenvolvimento → Conclusão!', curiosidade: 'Todo texto tem começo, meio e fim! A introdução apresenta, o desenvolvimento explica e a conclusão fecha. ✍️' },
          { tipo: 'multipla', pergunta: 'O que é uma sílaba tônica?', opcoes: ['A sílaba mais bonita', 'A primeira sílaba sempre', 'A sílaba pronunciada mais forte', 'A última sílaba sempre'], correta: 2, reacao_acerto: 'É a sílaba que falamos com mais força!', reacao_erro: 'Sílaba tônica é a pronunciada com mais força!', curiosidade: 'Em "café" o CA é a tônica. Em "óculos" o Ó é a tônica. Tente falar as palavras em voz alta! ☕' },
          { tipo: 'vf', pergunta: 'Um parágrafo começa com uma recuo (espaço) no início.', correta: true, reacao_acerto: 'Correto! O parágrafo tem recuo!', reacao_erro: 'Era VERDADEIRO! Parágrafos têm recuo no início.', curiosidade: 'O recuo ajuda nossos olhos a identificar onde começa um novo parágrafo. É como uma porta de entrada para nova ideia! 📖' },
          { tipo: 'multipla', pergunta: 'O plural de "pão" é:', opcoes: ['Pãos', 'Pões', 'Pães', 'Páos'], correta: 2, reacao_acerto: 'Pães! Correto!', reacao_erro: 'Era PÃES!', curiosidade: 'O português tem plurais diferentes! Mão→mãos, pão→pães, alemão→alemães. A língua é cheia de surpresas! 🍞' },
          { tipo: 'lacuna', pergunta: 'Complete a frase:', frase: 'Quando reescrevemos uma história com nossas palavras, fazemos uma _____ .', opcoes: ['Cópia', 'Paráfrase', 'Tradução', 'Poesia'], correta: 1, reacao_acerto: 'Paráfrase! Muito bem!', reacao_erro: 'Era PARÁFRASE!', curiosidade: 'Na paráfrase mantemos o sentido da ideia original mas mudamos as palavras. É diferente de copiar! 📚' },
          { tipo: 'multipla', pergunta: 'Qual é o gênero literário de "João e Maria"?', opcoes: ['Poema', 'Conto de fadas', 'Notícia', 'Bula de remédio'], correta: 1, reacao_acerto: 'Conto de fadas!', reacao_erro: 'João e Maria é um conto de fadas!', curiosidade: 'Contos de fadas geralmente começam com "Era uma vez..." e têm magia, heróis e finais felizes! 🧚' },
          { tipo: 'vf', pergunta: 'Ponto final (.) indica o fim de uma frase.', correta: true, reacao_acerto: 'Correto!', reacao_erro: 'Era VERDADEIRO!', curiosidade: 'O ponto final indica pausa longa e fim da ideia. Existem outros pontos: ponto de exclamação (!), interrogação (?) e reticências (...)! 📍' },
          { tipo: 'associar', pergunta: 'Ligue cada tipo de texto ao seu exemplo:', pares: [{ esq: '📰 Notícia', dir: 'Chuva forte na cidade' }, { esq: '📖 Conto', dir: 'Era uma vez um dragão...' }, { esq: '💌 Carta', dir: 'Querida amiga, tudo bem?' }, { esq: '📋 Lista', dir: '1-leite 2-pão 3-ovo' }], reacao_acerto: 'Você conhece os tipos de texto!', reacao_erro: 'Alguns pares estavam errados!', curiosidade: 'Cada texto tem um objetivo diferente! Notícia informa, conto entretém, carta comunica, lista organiza! 📝' },
          { tipo: 'completar', pergunta: 'Rima, ritmo e versos são características da _____.', resposta: 'poesia', dica: '(dica: po _ _ ia)', reacao_acerto: 'Poesia! Você é poeta!', reacao_erro: 'Era POESIA!', curiosidade: 'A poesia usa a musicalidade das palavras para emocionar! Muitas crianças fazem poesia sem perceber ao brincar! 🎶' },
          { tipo: 'multipla', pergunta: 'Em "O gato comeu o peixe", quem praticou a ação?', opcoes: ['O peixe', 'O comeu', 'O gato', 'A frase'], correta: 2, reacao_acerto: 'O gato é o sujeito da frase!', reacao_erro: 'Era O GATO! Ele praticou a ação de comer.', curiosidade: 'O sujeito é quem faz a ação do verbo. Pergunte: Quem comeu? O gato! Esse é o truque para achar o sujeito! 🐱' },
          { tipo: 'ordenar', pergunta: 'Ordene as letras do alfabeto:', itens: ['D', 'A', 'C', 'B'], ordemCorreta: [1, 3, 2, 0], reacao_acerto: 'A, B, C, D — alfabeto dominado!', reacao_erro: 'A ordem é A, B, C, D!', curiosidade: 'O alfabeto português tem 26 letras! Aprender a ordem ajuda a usar dicionários e enciclopédias. 📖' },
          { tipo: 'vf', pergunta: 'A vírgula serve para separar ideias dentro de uma frase.', correta: true, reacao_acerto: 'Correto! A vírgula organiza as ideias.', reacao_erro: 'Era VERDADEIRO!', curiosidade: 'A vírgula muda o sentido! "Vamos comer crianças!" vs "Vamos comer, crianças!" São frases bem diferentes! 😄' },
          { tipo: 'multipla', pergunta: 'O que é um dicionário?', opcoes: ['Um livro de histórias', 'Um livro com significados de palavras', 'Um livro de contas', 'Um livro de mapas'], correta: 1, reacao_acerto: 'O dicionário explica palavras!', reacao_erro: 'Dicionário é um livro com significados de palavras!', curiosidade: 'O maior dicionário da língua portuguesa tem mais de 400.000 palavras! O português é uma língua enorme! 📚' },
          { tipo: 'lacuna', pergunta: 'Identificar o tema principal:', frase: 'O _____ de um texto é a ideia mais importante que o autor quer nos contar.', opcoes: ['Título', 'Tema central', 'Personagem', 'Enredo'], correta: 1, reacao_acerto: 'Tema central! Você entende textos!', reacao_erro: 'Era TEMA CENTRAL!', curiosidade: 'Encontrar o tema central ajuda a entender qualquer texto. Pergunte: De que assunto esse texto trata? 🔍' },
        ,
          { tipo: 'multipla', pergunta: 'O que é um adjetivo?', opcoes: ['Palavra que indica ação', 'Palavra que dá nome às coisas', 'Palavra que caracteriza o substantivo', 'Palavra que liga ideias'], correta: 2, reacao_acerto: 'Adjetivo caracteriza o substantivo!', reacao_erro: 'Adjetivo CARACTERIZA o substantivo! Bonito, alto, azul são adjetivos.', curiosidade: 'Adjetivos concordam com o substantivo em gênero e número! Menino bonito, menina bonita, meninos bonitos. 🌟' },
          { tipo: 'vf', pergunta: '"Cachorro" e "cão" são sinônimos.', correta: true, reacao_acerto: 'Sim! Sinônimos têm significado próximo!', reacao_erro: 'Era VERDADEIRO! Cachorro e cão têm o mesmo significado.', curiosidade: 'Sinônimos são palavras com significados parecidos! Belo/bonito, rápido/veloz, gordo/obeso! 📚' },
          { tipo: 'multipla', pergunta: 'Qual é o plural correto de "cidadão"?', opcoes: ['Cidadães', 'Cidadãos', 'Cidadans', 'Cidadões'], correta: 1, reacao_acerto: 'Cidadãos! Correto!', reacao_erro: 'Era CIDADÃOS!', curiosidade: 'Palavras em -ão têm três plurais: -ões (campeões), -ãos (cidadãos), -ães (pães)! Cada caso é diferente! 🇧🇷' },
          { tipo: 'multipla', pergunta: 'A palavra "rapidamente" pertence a qual classe gramatical?', opcoes: ['Substantivo', 'Adjetivo', 'Advérbio', 'Verbo'], correta: 2, reacao_acerto: 'Advérbio! Modifica o verbo!', reacao_erro: 'Era ADVÉRBIO! Palavras terminadas em -mente geralmente são advérbios.', curiosidade: 'Advérbios modificam verbos, adjetivos ou outros advérbios! Rapidamente, lentamente, claramente, felizmente! 🏃' },
          { tipo: 'vf', pergunta: 'A letra "H" no início das palavras em português não tem som.', correta: true, reacao_acerto: 'Correto! O H inicial é mudo!', reacao_erro: 'Era VERDADEIRO! O H no início não tem som: hora, homem, hoje.', curiosidade: 'O H é traíçoeiro! No início é mudo (hora), mas no meio pode mudar o som: ch, lh, nh. 🔤' },
          { tipo: 'multipla', pergunta: 'O que é uma metáfora?', opcoes: ['Comparação com "como"', 'Identificação direta de uma coisa com outra', 'Repetição de palavras', 'Exagero proposital'], correta: 1, reacao_acerto: 'Metáfora é identificação direta!', reacao_erro: 'Metáfora é quando dizemos que algo É outra coisa! "Você é um leão" é metáfora.', curiosidade: 'Metáfora: "Ela é uma flor". Comparação: "Ela é como uma flor". A metáfora é mais direta e poética! 🌸' },
          { tipo: 'completar', pergunta: 'Palavras escritas iguais mas com significados diferentes chamam-se _____.', resposta: 'homônimos', dica: '(dica: homô _ _ _ os)', reacao_acerto: 'Homônimos! Excelente!', reacao_erro: 'Era HOMÔNIMOS!', curiosidade: 'Manga (fruta) e manga (de roupa) são homônimos! O contexto é fundamental para entender o significado. 🥭' },
          { tipo: 'multipla', pergunta: 'Qual é o sujeito da frase "Os alunos estudaram muito."?', opcoes: ['Estudaram', 'Muito', 'Os alunos', 'Alunos estudaram'], correta: 2, reacao_acerto: 'Os alunos é o sujeito!', reacao_erro: 'Era OS ALUNOS! O sujeito é quem pratica a ação.', curiosidade: 'Para achar o sujeito, pergunte: Quem estudaram muito? Os alunos! Esse truque funciona sempre! 📖' },
          { tipo: 'vf', pergunta: 'Todo verbo indica uma ação.', correta: false, reacao_acerto: 'Correto! Verbos também indicam estado e fenômeno!', reacao_erro: 'Era FALSO! Verbos também indicam estado (ser, estar) e fenômeno (chover, nevar).', curiosidade: 'Verbos de ação: correr, pular. Estado: ser, estar, parecer. Fenômeno: chover, amanhecer! 🌧️' },
          { tipo: 'lacuna', pergunta: 'Tipo de texto:', frase: 'Um texto que conta uma história imaginária com personagens e enredo é chamado de _____ .', opcoes: ['Notícia', 'Narrativo', 'Dissertativo', 'Instrucional'], correta: 1, reacao_acerto: 'Texto Narrativo!', reacao_erro: 'Era NARRATIVO!', curiosidade: 'Textos narrativos têm narrador, personagens, tempo, espaço e enredo! Os contos de fadas são textos narrativos clássicos! 📖' }
        ]
      },

      /* ── MATEMÁTICA ── */
      mat: {
        niveis: [
          { nome: '⭐ CONTADORZINHO', inicio: 0, fala: 'Vamos contar e calcular! A matemática é divertida!' },
          { nome: '⭐⭐ CALCULISTA', inicio: 5, fala: 'Nível 2! Os números são seus amigos!' },
          { nome: '⭐⭐⭐ GEÔMETRA', inicio: 10, fala: 'Nível 3! Formas e medidas te esperam!' },
          { nome: '💎 MESTRE DOS NÚMEROS', inicio: 15, fala: 'NÍVEL MESTRE! Você é um gênio da matemática!' },
        ],
        perguntas: [
          { tipo: 'multipla', pergunta: 'Quanto é 7 + 8?', opcoes: ['13', '14', '15', '16'], correta: 2, reacao_acerto: '7 + 8 = 15!', reacao_erro: 'Era 15! Conta nos dedos: 7... 8, 9, 10, 11, 12, 13, 14, 15!', curiosidade: 'Uma dica: 7+8 = 7+7+1 = 14+1 = 15! Decompor os números facilita o cálculo mental! 🧮' },
          { tipo: 'vf', pergunta: 'O número 42 é par.', correta: true, reacao_acerto: 'Sim! 42 é par porque termina em 2!', reacao_erro: 'Era VERDADEIRO! Números que terminam em 0,2,4,6,8 são pares.', curiosidade: 'Números pares podem ser divididos em 2 grupos iguais sem sobrar nada. 42 ÷ 2 = 21 exato! ✌️' },
          { tipo: 'multipla', pergunta: 'Qual fração representa a metade?', opcoes: ['1/3', '1/4', '1/2', '2/3'], correta: 2, reacao_acerto: '1/2 é a metade! Um de dois!', reacao_erro: 'Era 1/2! Metade significa dividir em 2 partes iguais.', curiosidade: 'Se você parte uma pizza ao meio, cada pedaço é 1/2. Fração é divisão! 🍕' },
          { tipo: 'completar', pergunta: 'A tabuada de multiplicação de qualquer número por zero é sempre _____.', resposta: 'zero', dica: '(dica: z _ _ o)', reacao_acerto: 'Zero! Qualquer coisa × 0 = 0!', reacao_erro: 'Era ZERO!', curiosidade: 'Se você tem 5 sacolas mas cada uma tem 0 balas, você tem 0 balas. Faz sentido né? 🎒' },
          { tipo: 'ordenar', pergunta: 'Coloque em ordem CRESCENTE (menor para maior):', itens: ['75', '12', '38', '99'], ordemCorreta: [1, 2, 0, 3], reacao_acerto: '12, 38, 75, 99 — ordem crescente correta!', reacao_erro: 'A ordem crescente era: 12, 38, 75, 99!', curiosidade: 'Crescente vem de crescer! Os números aumentam. Decrescente é o contrário, eles diminuem. 📈' },
          { tipo: 'multipla', pergunta: 'Quantos lados tem um triângulo?', opcoes: ['2', '3', '4', '5'], correta: 1, reacao_acerto: 'Triângulo tem 3 lados!', reacao_erro: 'TRI-ângulo! TRI = 3! Três lados.', curiosidade: 'TRI vem do latim e significa 3! Triciclo tem 3 rodas, tripé tem 3 pés, triângulo tem 3 lados! 📐' },
          { tipo: 'vf', pergunta: '1 quilograma (kg) é igual a 1000 gramas (g).', correta: true, reacao_acerto: 'Certinho! 1 kg = 1000 g!', reacao_erro: 'Era VERDADEIRO! 1 kg = 1000 g.', curiosidade: 'Kilo vem do grego e significa 1000! Quilômetro = 1000 metros, quilograma = 1000 gramas! 💪' },
          { tipo: 'multipla', pergunta: 'Qual operação é o contrário da adição?', opcoes: ['Multiplicação', 'Divisão', 'Subtração', 'Potenciação'], correta: 2, reacao_acerto: 'A subtração desfaz a adição!', reacao_erro: 'Era SUBTRAÇÃO! Adição soma, subtração tira.', curiosidade: 'Operações inversas se desfazem: 5+3=8 e 8-3=5! A multiplicação e divisão também são inversas. 🔄' },
          { tipo: 'multipla', pergunta: 'Um hexágono tem quantos lados?', opcoes: ['5', '6', '7', '8'], correta: 1, reacao_acerto: 'Hexágono tem 6 lados!', reacao_erro: 'HEXA = 6! Hexágono tem 6 lados.', curiosidade: 'A colmeia das abelhas é formada por hexágonos! A natureza escolheu esse formato pois é o mais eficiente para usar espaço! 🐝' },
          { tipo: 'lacuna', pergunta: 'Calcule:', frase: 'Se tenho 3 caixas com 4 lápis cada uma, tenho _____ lápis ao todo.', opcoes: ['7', '10', '12', '15'], correta: 2, reacao_acerto: '3 × 4 = 12 lápis!', reacao_erro: 'Era 12! 3 caixas × 4 lápis = 12 lápis!', curiosidade: 'Multiplicação é uma soma repetida! 3×4 = 4+4+4 = 12. É mais rápido que somar várias vezes! ✏️' },
          { tipo: 'vf', pergunta: 'O número 100 é composto por 1 centena, 0 dezenas e 0 unidades.', correta: true, reacao_acerto: 'Correto! 1 centena = 100!', reacao_erro: 'Era VERDADEIRO!', curiosidade: 'Nossa forma de escrever números usa a base 10: unidades, dezenas, centenas, milhares... Cada posição vale 10× mais! 💯' },
          { tipo: 'multipla', pergunta: 'Qual é a metade de 40?', opcoes: ['10', '15', '20', '25'], correta: 2, reacao_acerto: 'A metade de 40 é 20!', reacao_erro: 'Era 20! 40 ÷ 2 = 20.', curiosidade: 'Para achar a metade de um número par, divida por 2! Metade de 100 = 50, metade de 80 = 40! 🔢' },
          { tipo: 'ordenar', pergunta: 'Ordene as unidades de tempo do menor para o maior:', itens: ['Semana', 'Minuto', 'Ano', 'Dia'], ordemCorreta: [1, 3, 0, 2], reacao_acerto: 'Minuto → Dia → Semana → Ano!', reacao_erro: 'A ordem era: Minuto → Dia → Semana → Ano!', curiosidade: '1 dia = 24 horas, 1 semana = 7 dias, 1 mês ≈ 30 dias, 1 ano = 365 dias! O tempo tem sua hierarquia! ⏰' },
          { tipo: 'multipla', pergunta: 'O que é perímetro?', opcoes: ['A área de dentro de uma figura', 'A soma dos lados de uma figura', 'A altura de uma figura', 'O número de lados'], correta: 1, reacao_acerto: 'Perímetro é a soma de todos os lados!', reacao_erro: 'Perímetro = soma dos lados! É a medida do contorno.', curiosidade: 'Para cercar um terreno, você precisa saber o perímetro! Uma fazenda quadrada de 100m de lado tem perímetro de 400m! 🌾' },
          { tipo: 'associar', pergunta: 'Ligue cada forma geométrica ao número de lados:', pares: [{ esq: 'Triângulo', dir: '3 lados' }, { esq: 'Quadrado', dir: '4 lados' }, { esq: 'Pentágono', dir: '5 lados' }, { esq: 'Hexágono', dir: '6 lados' }], reacao_acerto: 'Você conhece todas as formas!', reacao_erro: 'Alguns pares estavam errados!', curiosidade: 'A palavra -gono vem do grego e significa ângulo! Polígono = muitos ângulos. Polvo não conta! 😄' },
          { tipo: 'vf', pergunta: 'Na divisão, o resultado se chama quociente.', correta: true, reacao_acerto: 'Correto! 10 ÷ 2 = 5, e 5 é o quociente!', reacao_erro: 'Era VERDADEIRO! O resultado da divisão é o quociente.', curiosidade: 'Na adição o resultado é a soma. Na subtração é a diferença. Na multiplicação é o produto. Na divisão é o quociente! 📊' },
          { tipo: 'multipla', pergunta: 'Quanto é 9 × 9?', opcoes: ['72', '81', '80', '91'], correta: 1, reacao_acerto: '9 × 9 = 81!', reacao_erro: 'Era 81! A tabuada do 9 tem um truque: a soma dos algarismos sempre dá 9!', curiosidade: 'Truque da tabuada do 9: 9×2=18 (1+8=9), 9×3=27 (2+7=9), 9×4=36 (3+6=9)! A soma dos dígitos sempre é 9! 🤯' },
          { tipo: 'completar', pergunta: 'A dezena que vem depois de 80 é _____.', resposta: 'noventa', dica: '(dica: nove _ _ a)', reacao_acerto: 'Noventa (90)!', reacao_erro: 'Era NOVENTA (90)!', curiosidade: 'A sequência das dezenas: 10, 20, 30, 40, 50, 60, 70, 80, 90, 100! Cada uma é 10 a mais que a anterior! 🔟' },
          { tipo: 'lacuna', pergunta: 'Geometria:', frase: 'Um quadrado tem _____ ângulos retos (de 90°).', opcoes: ['2', '3', '4', '6'], correta: 2, reacao_acerto: '4 ângulos retos! Quadrado perfeito!', reacao_erro: 'Era 4! Todo quadrado tem 4 cantos de 90°.', curiosidade: 'Um ângulo reto é como o canto de uma folha de papel ou de uma parede! O símbolo é □ no canto. 📐' },
          { tipo: 'multipla', pergunta: 'Qual é o maior número de dois dígitos?', opcoes: ['89', '90', '98', '99'], correta: 3, reacao_acerto: '99 é o maior número de dois dígitos!', reacao_erro: 'Era 99! Depois vem 100, que já tem três dígitos!', curiosidade: 'Após o 99 vem o 100, que inaugura os números de 3 dígitos! O maior de 3 dígitos é o 999. O de 4 é 9999! 💯' },
        ,
          { tipo: 'multipla', pergunta: 'Quantos minutos há em uma hora?', opcoes: ['30', '45', '60', '100'], correta: 2, reacao_acerto: '60 minutos em uma hora!', reacao_erro: 'Uma hora tem 60 MINUTOS!', curiosidade: 'O sistema de 60 minutos vem dos babilônios! Eles usavam base 60. Daí também vêm os 360° do círculo! ⏱️' },
          { tipo: 'vf', pergunta: '3 × 4 = 4 × 3 (a multiplicação é comutativa).', correta: true, reacao_acerto: 'Correto! A ordem não muda o resultado!', reacao_erro: 'Era VERDADEIRO! Na multiplicação, a ordem dos fatores não altera o produto.', curiosidade: 'Comutatividade vale para adição e multiplicação, mas NÃO para subtração e divisão! 5-3≠3-5 e 10÷2≠2÷10! 🔢' },
          { tipo: 'multipla', pergunta: 'Qual é o dobro de 45?', opcoes: ['80', '85', '90', '95'], correta: 2, reacao_acerto: 'O dobro de 45 é 90!', reacao_erro: 'Dobro de 45 = 45 × 2 = 90!', curiosidade: 'Dobro = ×2. Triplo = ×3. Metade = ÷2. Esses são os cálculos mais usados no dia a dia! 💡' },
          { tipo: 'multipla', pergunta: 'Quantas faces tem um cubo?', opcoes: ['4', '6', '8', '12'], correta: 1, reacao_acerto: 'O cubo tem 6 faces!', reacao_erro: 'O CUBO tem 6 faces! Como um dado comum!', curiosidade: 'Cubo: 6 faces, 12 arestas, 8 vértices. Um dado é um cubo perfeito! Cada face é um quadrado igual. 🎲' },
          { tipo: 'vf', pergunta: '100 ÷ 4 = 25.', correta: true, reacao_acerto: 'Correto! 100 ÷ 4 = 25!', reacao_erro: 'Era VERDADEIRO! 100 ÷ 4 = 25.', curiosidade: 'Outro jeito de pensar: 4 × 25 = 100. Divisão e multiplicação são operações inversas! 💯' },
          { tipo: 'multipla', pergunta: 'Qual operação resolve: "Pedro tinha R$50 e gastou R$18. Quanto restou?"', opcoes: ['Adição', 'Subtração', 'Multiplicação', 'Divisão'], correta: 1, reacao_acerto: 'Subtração! 50 - 18 = 32!', reacao_erro: 'Era SUBTRAÇÃO! Quando "gasta/perde" usamos subtração.', curiosidade: 'Palavras-chave: "ganhou" → adição. "gastou/perdeu" → subtração. "vezes/cada" → multiplicação! 💰' },
          { tipo: 'lacuna', pergunta: 'Sequência numérica:', frase: 'Na sequência 3, 6, 9, 12... a diferença entre os termos é sempre _____.', opcoes: ['2', '3', '4', '5'], correta: 1, reacao_acerto: '3! É a tabuada do 3!', reacao_erro: 'Era 3! 6-3=3, 9-6=3, 12-9=3!', curiosidade: 'Essa é uma progressão aritmética com razão 3! É a tabuada do 3 em sequência. Progressão significa cada número segue uma regra. 🔢' },
          { tipo: 'vf', pergunta: 'Um quadrilátero tem exatamente 4 lados.', correta: true, reacao_acerto: 'Correto! Quadri = 4!', reacao_erro: 'Era VERDADEIRO! Quadrilátero vem de "quadri" (4) + "látero" (lado).', curiosidade: 'Quadriláteros: quadrado, retângulo, losango, trapézio, paralelogramo — todos têm 4 lados! 📐' },
          { tipo: 'multipla', pergunta: 'Qual é a metade de 78?', opcoes: ['37', '38', '39', '40'], correta: 2, reacao_acerto: '78 ÷ 2 = 39!', reacao_erro: 'Era 39! 78 ÷ 2 = 39.', curiosidade: 'Para dividir por 2, você pode dividir as dezenas e unidades separadas: 70÷2=35 e 8÷2=4, logo 35+4=39! 🧮' },
          { tipo: 'completar', pergunta: 'O ângulo que mede exatamente 90° é chamado de ângulo _____.', resposta: 'reto', dica: '(dica: r _ to)', reacao_acerto: 'Ângulo reto! 90° exatos!', reacao_erro: 'Era RETO!', curiosidade: 'Ângulo reto = 90°. Agudo = menor que 90°. Obtuso = entre 90° e 180°. Raso = 180°. Usado em esquadros e cantos de parede! 📐' }
        ]
      },

      /* ── CIÊNCIAS ── */
      ciencias: {
        niveis: [
          { nome: '⭐ CURIOSO DA NATUREZA', inicio: 0, fala: 'Cientistas curiosos mudam o mundo! Vamos explorar a natureza!' },
          { nome: '⭐⭐ BIÓLOGO MIRIM', inicio: 5, fala: 'Nível 2! Os seres vivos têm muito para nos ensinar!' },
          { nome: '⭐⭐⭐ EXPLORADOR', inicio: 10, fala: 'Nível 3! A ciência é cheia de surpresas!' },
          { nome: '💎 CIENTISTA MESTRE', inicio: 15, fala: 'NÍVEL MESTRE! Você é um cientista incrível!' },
        ],
        perguntas: [
          { tipo: 'multipla', pergunta: 'O que as plantas precisam para fazer fotossíntese?', opcoes: ['Água, luz e gelo', 'Luz, água e ar (CO₂)', 'Chuva, sombra e terra', 'Luz, açúcar e vento'], correta: 1, reacao_acerto: 'Luz, água e gás carbônico! Correto!', reacao_erro: 'As plantas precisam de luz, água e CO₂!', curiosidade: 'As folhas são verdadeiras fábricas! Elas captam a luz do sol, absorvem CO₂ do ar e usam água para produzir açúcar e liberar O₂. 🌱' },
          { tipo: 'vf', pergunta: 'O coração é responsável por bombear o sangue pelo corpo.', correta: true, reacao_acerto: 'Sim! O coração é nossa bomba de sangue!', reacao_erro: 'Era VERDADEIRO! O coração bombeia o sangue.', curiosidade: 'O coração de uma criança bate cerca de 80-100 vezes por minuto! Em toda uma vida, bate mais de 2 bilhões de vezes! ❤️' },
          { tipo: 'multipla', pergunta: 'Qual animal é um mamífero?', opcoes: ['Jacaré', 'Tubarão', 'Baleia', 'Pinguim'], correta: 2, reacao_acerto: 'A baleia é mamífero! Amamenta seus filhotes!', reacao_erro: 'Era a BALEIA! Mamíferos amamentam os filhotes.', curiosidade: 'Mamífero vem de mamá! São animais que amamentam os filhotes com leite. Humanos, cachorros, baleias e golfinhos são mamíferos! 🐋' },
          { tipo: 'ordenar', pergunta: 'Coloque as fases da metamorfose da borboleta em ordem:', itens: ['Borboleta', 'Ovo', 'Casulo/Pupa', 'Lagarta'], ordemCorreta: [1, 3, 2, 0], reacao_acerto: 'Ovo → Lagarta → Casulo → Borboleta!', reacao_erro: 'A ordem era: Ovo → Lagarta → Casulo → Borboleta!', curiosidade: 'A metamorfose é uma transformação incrível! A lagarta se fecha no casulo e se reconstrói completamente, saindo como borboleta! 🦋' },
          { tipo: 'vf', pergunta: 'Os ossos do corpo humano formam o esqueleto.', correta: true, reacao_acerto: 'Sim! O esqueleto sustenta nosso corpo!', reacao_erro: 'Era VERDADEIRO!', curiosidade: 'O corpo humano adulto tem 206 ossos! O menor osso fica no ouvido e tem menos de 3mm. O maior é o fêmur (coxa)! 🦴' },
          { tipo: 'multipla', pergunta: 'O que é uma cadeia alimentar?', opcoes: ['Uma corrente de ouro', 'A relação de quem come quem na natureza', 'Um tipo de corrente de ferro', 'Uma sequência de plantas'], correta: 1, reacao_acerto: 'Cadeia alimentar mostra quem come quem!', reacao_erro: 'Cadeia alimentar é a relação de quem come quem na natureza!', curiosidade: 'Grama → Gafanhoto → Sapo → Cobra → Gavião! Cada ser vivo tem seu lugar na cadeia. Se um desaparece, afeta todos! 🌿' },
          { tipo: 'multipla', pergunta: 'Qual órgão é responsável pela respiração?', opcoes: ['Coração', 'Estômago', 'Pulmão', 'Fígado'], correta: 2, reacao_acerto: 'Os pulmões nos fazem respirar!', reacao_erro: 'Era o PULMÃO! Ele capta o oxigênio do ar.', curiosidade: 'Respiramos cerca de 20.000 vezes por dia! Os pulmões juntos têm a superfície de uma quadra de tênis se abertos! 🫁' },
          { tipo: 'lacuna', pergunta: 'Os seres vivos são formados por:', frase: 'A menor unidade dos seres vivos se chama _____ .', opcoes: ['Átomo', 'Célula', 'Tecido', 'Órgão'], correta: 1, reacao_acerto: 'Célula! A unidade básica da vida!', reacao_erro: 'Era CÉLULA!', curiosidade: 'Células são como tijolinhos da vida! Algumas plantas têm células visíveis a olho nu. Nosso corpo tem 37 trilhões delas! 🔬' },
          { tipo: 'vf', pergunta: 'A água é o único líquido encontrado no planeta Terra.', correta: false, reacao_acerto: 'Correto! Há outros líquidos como petróleo!', reacao_erro: 'Era FALSO! Existem muitos outros líquidos: petróleo, mercúrio, sucos...', curiosidade: 'A Terra tem muitos líquidos naturais! Mas a água é o mais especial pois sustenta a vida como conhecemos. 💧' },
          { tipo: 'multipla', pergunta: 'O que é um ecosistema?', opcoes: ['Uma espécie animal', 'Conjunto de seres vivos e o ambiente onde vivem', 'Um tipo de planta exótica', 'Somente os animais de uma floresta'], correta: 1, reacao_acerto: 'Ecossistema é seres vivos + ambiente!', reacao_erro: 'Ecossistema = seres vivos + seu ambiente juntos!', curiosidade: 'A floresta, o oceano, o deserto, a savana — cada um é um ecossistema com suas regras próprias! 🌍' },
          { tipo: 'associar', pergunta: 'Ligue cada animal ao que ele come:', pares: [{ esq: '🦁 Leão', dir: 'Outros animais' }, { esq: '🐄 Vaca', dir: 'Plantas/grama' }, { esq: '🐻 Urso', dir: 'Carne e vegetais' }, { esq: '🐛 Lagarta', dir: 'Folhas' }], reacao_acerto: 'Você conhece as cadeias alimentares!', reacao_erro: 'Alguns pares estavam errados!', curiosidade: 'Carnívoro come carne, herbívoro come plantas, onívoro come os dois. Humanos somos onívoros! 🥩🥦' },
          { tipo: 'vf', pergunta: 'As plantas produzem oxigênio durante a fotossíntese.', correta: true, reacao_acerto: 'Sim! As plantas são nossas fábricas de O₂!', reacao_erro: 'Era VERDADEIRO! A fotossíntese libera oxigênio!', curiosidade: 'Uma árvore adulta produz oxigênio suficiente para 10 pessoas respirarem por dia! Por isso as florestas são tão importantes! 🌳' },
          { tipo: 'completar', pergunta: 'O processo pelo qual a água vira vapor é chamado de _____.', resposta: 'evaporação', dica: '(dica: eva _ _ _ _ _ ão)', reacao_acerto: 'Evaporação! Correto!', reacao_erro: 'Era EVAPORAÇÃO!', curiosidade: 'O sol esquenta os oceanos, a água evapora, forma nuvens e cai como chuva. O ciclo da água não para nunca! ☁️' },
          { tipo: 'multipla', pergunta: 'Qual é o planeta onde vivemos?', opcoes: ['Marte', 'Vênus', 'Terra', 'Mercúrio'], correta: 2, reacao_acerto: 'Vivemos na Terra! O planeta azul!', reacao_erro: 'Era a TERRA! Vista do espaço, parece uma bolinha azul.', curiosidade: 'A Terra é chamada de planeta azul porque 71% da sua superfície é coberta por água! Vista do espaço, ela parece uma bola de gude azul! 🌍' },
          { tipo: 'lacuna', pergunta: 'Qual é a função?', frase: 'O sistema _____ é responsável por transportar oxigênio pelo corpo através do sangue.', opcoes: ['Nervoso', 'Digestório', 'Circulatório', 'Respiratório'], correta: 2, reacao_acerto: 'Sistema circulatório! Correto!', reacao_erro: 'Era CIRCULATÓRIO!', curiosidade: 'O sistema circulatório é como uma rede de estradas! O coração bombeia, as artérias e veias são as estradas e o sangue é o carro! 🚗' },
          { tipo: 'vf', pergunta: 'A Lua é uma estrela.', correta: false, reacao_acerto: 'Correto! A Lua é um satélite natural!', reacao_erro: 'Era FALSO! A Lua é um satélite natural da Terra, não uma estrela!', curiosidade: 'A Lua não brilha com luz própria! Ela reflete a luz do Sol, como um espelho. O único satélite natural da Terra! 🌕' },
          { tipo: 'multipla', pergunta: 'O que acontece na digestão?', opcoes: ['Os pulmões filtram o ar', 'O estômago transforma alimentos em nutrientes', 'O coração bombeia sangue', 'Os ossos crescem'], correta: 1, reacao_acerto: 'A digestão transforma alimentos em nutrientes!', reacao_erro: 'A digestão acontece no estômago e intestino!', curiosidade: 'A digestão começa na boca! Os dentes trituram e a saliva já começa a quebrar os alimentos. O processo todo dura cerca de 24 horas! 🦷' },
          { tipo: 'ordenar', pergunta: 'Ordene os estados físicos da água da menor para a maior temperatura:', itens: ['Vapor (gás)', 'Gelo (sólido)', 'Água líquida'], ordemCorreta: [1, 2, 0], reacao_acerto: 'Gelo → Água → Vapor! Correto!', reacao_erro: 'A ordem era: Gelo (sólido) → Água (líquido) → Vapor (gás)!', curiosidade: 'A água é especial por ser o único elemento encontrado em 3 estados na natureza! Gelo, água e vapor convivem no planeta! 💧' },
          { tipo: 'multipla', pergunta: 'Qual grupo de plantas NÃO tem flores?', opcoes: ['Roseiras', 'Samambaias', 'Girassóis', 'Jasmins'], correta: 1, reacao_acerto: 'Samambaias não têm flores!', reacao_erro: 'SAMAMBAIAS não têm flores! São plantas mais antigas que as flores.', curiosidade: 'Samambaias existem há mais de 360 milhões de anos, muito antes das flores aparecerem! Se reproduzem por esporos, não sementes! 🌿' },
          { tipo: 'vf', pergunta: 'A energia solar é renovável.', correta: true, reacao_acerto: 'Sim! O sol não vai acabar tão cedo!', reacao_erro: 'Era VERDADEIRO! O sol dura bilhões de anos!', curiosidade: 'O Sol tem 5 bilhões de anos e deve durar mais 5 bilhões! Energia solar, eólica e hidrelétrica são renováveis. Petróleo não é! ☀️' },
        ,
          { tipo: 'multipla', pergunta: 'Qual planeta é conhecido como o "Planeta Vermelho"?', opcoes: ['Vênus', 'Júpiter', 'Marte', 'Saturno'], correta: 2, reacao_acerto: 'Marte, o Planeta Vermelho!', reacao_erro: 'Era MARTE! Sua cor vem do óxido de ferro (ferrugem) no solo.', curiosidade: 'Marte é vermelho por causa do óxido de ferro (ferrugem) em sua superfície! Há sondas exploradoras lá agora mesmo! 🔴' },
          { tipo: 'vf', pergunta: 'Baleias são mamíferas, não peixes.', correta: true, reacao_acerto: 'Correto! Baleias são mamíferos!', reacao_erro: 'Era VERDADEIRO! A baleia amamenta os filhotes e respira ar, então é mamífero!', curiosidade: 'Baleias precisam subir à superfície para respirar! Elas vivem no mar mas já foram animais terrestres há 50 milhões de anos! 🐋' },
          { tipo: 'multipla', pergunta: 'O que os herbívoros comem?', opcoes: ['Somente outros animais', 'Somente plantas', 'Plantas e animais', 'Somente fungos'], correta: 1, reacao_acerto: 'Herbívoros comem plantas!', reacao_erro: 'HERBÍVOROS comem PLANTAS! Herbi = erva (planta).', curiosidade: 'Vaca, coelho, zebra, elefante são herbívoros. Precisam comer muitas horas por dia para obter energia das plantas! 🌿' },
          { tipo: 'completar', pergunta: 'A camada mais externa da Terra se chama _____.', resposta: 'crosta', dica: '(dica: c _ _ sta)', reacao_acerto: 'Crosta! A camada onde vivemos!', reacao_erro: 'Era CROSTA!', curiosidade: 'A Terra tem 4 camadas: crosta, manto, núcleo externo e núcleo interno. O núcleo chega a 5.000°C! 🌍' },
          { tipo: 'vf', pergunta: 'A teia de aranha é mais resistente que o aço do mesmo diâmetro.', correta: true, reacao_acerto: 'Correto! A seda de aranha é incrível!', reacao_erro: 'Era VERDADEIRO! A seda da aranha é mais resistente que o aço!', curiosidade: 'Cientistas estudam a seda de aranha para criar materiais super-resistentes! É mais forte que o kevlar (usado em coletes à prova de bala)! 🕷️' },
          { tipo: 'multipla', pergunta: 'Qual parte da planta absorve água do solo?', opcoes: ['Folhas', 'Flores', 'Raízes', 'Caule'], correta: 2, reacao_acerto: 'As raízes absorvem água!', reacao_erro: 'As RAÍZES absorvem água e nutrientes do solo!', curiosidade: 'As raízes podem ser tão profundas quanto a planta é alta! Uma figueira pode ter raízes de 120 metros! 🌱' },
          { tipo: 'multipla', pergunta: 'O que é um fóssil?', opcoes: ['Um mineral precioso', 'Restos ou marcas de seres vivos preservados em rocha', 'Um meteorito', 'Um cristal de sal'], correta: 1, reacao_acerto: 'Fóssil são restos preservados!', reacao_erro: 'Fóssil são restos ou marcas de seres vivos de antigamente preservados na rocha!', curiosidade: 'Fósseis podem ter milhões de anos! Através deles descobrimos que os pássaros são descendentes dos dinossauros! 🦖' },
          { tipo: 'lacuna', pergunta: 'Sistema locomotor:', frase: 'O sistema _____ é responsável pelo suporte e movimento do corpo (ossos e músculos).', opcoes: ['Circulatório', 'Digestório', 'Locomotor', 'Respiratório'], correta: 2, reacao_acerto: 'Sistema Locomotor!', reacao_erro: 'Era LOCOMOTOR!', curiosidade: 'O sistema locomotor tem ossos (esqueleto) e músculos trabalhando juntos! Músculos puxam os ossos para gerar movimento. 💪' },
          { tipo: 'vf', pergunta: 'O sol é considerado uma estrela de tamanho médio.', correta: true, reacao_acerto: 'Correto! Existem estrelas muito maiores!', reacao_erro: 'Era VERDADEIRO! O sol é uma anã amarela, menor que muitas outras estrelas.', curiosidade: 'A estrela UY Scuti é 1.700 vezes maior que o Sol! Se fosse no lugar do sol, engoleria até Júpiter. O universo é imenso! ☀️' },
          { tipo: 'multipla', pergunta: 'O que é adaptação nos seres vivos?', opcoes: ['Processo de extinção', 'Características que ajudam a sobreviver no ambiente', 'Tipo de reprodução', 'Migração para outro lugar'], correta: 1, reacao_acerto: 'Adaptação é ter características para sobreviver!', reacao_erro: 'Adaptação são características que ajudam o ser vivo a sobreviver no seu ambiente!', curiosidade: 'O camelo armazena gordura na corcova; o peixe tem guelras para respirar na água. Cada adaptação levou milhões de anos! 🐪' }
        ]
      },

      /* ── HISTÓRIA ── */
      historia: {
        niveis: [
          { nome: '⭐ EXPLORADOR DO TEMPO', inicio: 0, fala: 'Vamos viajar pelo tempo! A história é incrível!' },
          { nome: '⭐⭐ CRONISTA', inicio: 5, fala: 'Nível 2! Cada época tem suas histórias!' },
          { nome: '⭐⭐⭐ HISTORIADOR', inicio: 10, fala: 'Nível 3! Você está desvendando a história!' },
          { nome: '💎 MESTRE DO TEMPO', inicio: 15, fala: 'NÍVEL MESTRE! Você conhece a história como ninguém!' },
        ],
        perguntas: [
          { tipo: 'multipla', pergunta: 'Quem foi o primeiro presidente do Brasil?', opcoes: ['Dom Pedro II', 'Getúlio Vargas', 'Deodoro da Fonseca', 'Lula'], correta: 2, reacao_acerto: 'Deodoro da Fonseca foi o 1º presidente!', reacao_erro: 'Era Deodoro da Fonseca (1889)!', curiosidade: 'Manuel Deodoro da Fonseca proclamou a República em 15 de novembro de 1889 e se tornou o 1º presidente do Brasil! 🇧🇷' },
          { tipo: 'vf', pergunta: 'O Brasil foi colônia de Portugal por cerca de 300 anos.', correta: true, reacao_acerto: 'Correto! De 1500 a 1822 foram 322 anos!', reacao_erro: 'Era VERDADEIRO! Do descobrimento (1500) à independência (1822).', curiosidade: 'O Brasil ficou sob domínio português de 1500 a 1822: 322 anos! A língua portuguesa que falamos hoje é herança desse período! 🇵🇹' },
          { tipo: 'multipla', pergunta: 'Em que data é comemorada a Independência do Brasil?', opcoes: ['15 de novembro', '7 de setembro', '22 de abril', '21 de abril'], correta: 1, reacao_acerto: '7 de setembro de 1822!', reacao_erro: 'Era 7 de setembro! "Independência ou Morte!"', curiosidade: 'Dom Pedro I às margens do Rio Ipiranga em 7/9/1822 gritou "Independência ou Morte!". Por isso comemoramos nesse dia! 🗡️' },
          { tipo: 'completar', pergunta: 'O imperador que aboliu a escravidão no Brasil foi Dom Pedro _____.', resposta: 'segundo', dica: '(dica: seg _ _ _ o)', reacao_acerto: 'Dom Pedro Segundo (II)!', reacao_erro: 'Era DOM PEDRO SEGUNDO (II)!', curiosidade: 'A Princesa Isabel assinou a Lei Áurea em 13 de maio de 1888, abolindo a escravidão! Mas foi Dom Pedro II quem incentivou e apoiou esse processo! 📜' },
          { tipo: 'multipla', pergunta: 'Qual povo habitava o Brasil antes dos portugueses chegarem?', opcoes: ['Astecas', 'Maias', 'Indígenas brasileiros', 'Incas'], correta: 2, reacao_acerto: 'Os povos indígenas brasileiros!', reacao_erro: 'Eram os INDÍGENAS BRASILEIROS! Centenas de etnias.', curiosidade: 'Quando os portugueses chegaram em 1500, havia cerca de 5 milhões de indígenas no Brasil, em mais de 1000 povos diferentes! 🏹' },
          { tipo: 'vf', pergunta: 'Os africanos escravizados trouxeram muito da cultura que temos hoje no Brasil.', correta: true, reacao_acerto: 'Verdade! Música, culinária, palavras vêm de África!', reacao_erro: 'Era VERDADEIRO! Samba, acarajé, capoeira são heranças africanas!', curiosidade: 'Mais de 5 milhões de africanos foram trazidos ao Brasil à força. Trouxeram ritmos, religiões, palavras e sabores que adoramos! 🎶' },
          { tipo: 'multipla', pergunta: 'O que foi a "Proclamação da República" no Brasil?', opcoes: ['A independência de Portugal', 'A abolição da escravidão', 'A troca do governo monárquico pelo republicano', 'A chegada dos portugueses'], correta: 2, reacao_acerto: 'A monarquia virou república em 1889!', reacao_erro: 'A Proclamação da República trocou o imperador pelo presidente!', curiosidade: 'Antes de 1889, o Brasil era governado por um imperador. Depois, passou a ter um presidente eleito — isso é a república! 🎩' },
          { tipo: 'ordenar', pergunta: 'Coloque os fatos históricos em ordem cronológica:', itens: ['Independência do Brasil (1822)', 'Abolição da escravidão (1888)', 'Chegada dos portugueses (1500)', 'Proclamação da República (1889)'], ordemCorreta: [2, 0, 1, 3], reacao_acerto: 'Você sabe a ordem da história!', reacao_erro: 'A ordem era: 1500 → 1822 → 1888 → 1889!', curiosidade: 'A linha do tempo ajuda a entender que os acontecimentos têm causa e efeito! Um evento influencia o próximo! ⏳' },
          { tipo: 'multipla', pergunta: 'Qual é o monumento histórico da cidade de Ouro Preto?', opcoes: ['Cristo Redentor', 'Museu do Ipiranga', 'Aleijadinho e suas igrejas barrocas', 'Torre Eiffel brasileira'], correta: 2, reacao_acerto: 'As obras do Aleijadinho!', reacao_erro: 'Ouro Preto é famosa pelas igrejas barrocas do Aleijadinho!', curiosidade: 'Antônio Francisco Lisboa, o Aleijadinho, criou obras incríveis mesmo com uma doença que afetava suas mãos. Ouro Preto é Patrimônio da Humanidade! 🏛️' },
          { tipo: 'vf', pergunta: 'A Semana de Arte Moderna de 1922 foi realizada em São Paulo.', correta: true, reacao_acerto: 'Sim! Foi em São Paulo em fevereiro de 1922!', reacao_erro: 'Era VERDADEIRO! Foi no Teatro Municipal de São Paulo.', curiosidade: 'A Semana de 22 revolucionou a arte brasileira! Artistas queriam criar algo tipicamente brasileiro, sem copiar a Europa. Tarsila do Amaral e Oswald de Andrade participaram! 🎨' },
          { tipo: 'multipla', pergunta: 'Qual herói brasileiro lutou contra a escravidão e virou lenda?', opcoes: ['Tiradentes', 'Zumbi dos Palmares', 'Padre Cícero', 'Dom João VI'], correta: 1, reacao_acerto: 'Zumbi dos Palmares, herói da liberdade!', reacao_erro: 'Era ZUMBI DOS PALMARES! Líder do Quilombo dos Palmares.', curiosidade: 'Zumbi dos Palmares liderou o maior quilombo do Brasil, com 30.000 pessoas livres! Morreu em 1695 lutando pela liberdade. 20 de novembro é o Dia da Consciência Negra! ✊' },
          { tipo: 'lacuna', pergunta: 'Quem chegou ao Brasil:', frase: 'Pedro Álvares Cabral chegou ao Brasil em _____ .', opcoes: ['1200', '1492', '1500', '1600'], correta: 2, reacao_acerto: '1500! Correto!', reacao_erro: 'Era 1500!', curiosidade: 'Em 22 de abril de 1500, a frota de Cabral avistou o Monte Pascoal na Bahia. Essa data marca o início do Brasil como conhecemos! ⛵' },
          { tipo: 'associar', pergunta: 'Ligue o herói histórico à sua conquista:', pares: [{ esq: 'Tiradentes', dir: 'Inconfidência Mineira' }, { esq: 'Dom Pedro I', dir: 'Independência do Brasil' }, { esq: 'Princesa Isabel', dir: 'Abolição da escravidão' }, { esq: 'Deodoro da Fonseca', dir: 'Proclamação da República' }], reacao_acerto: 'Você conhece os heróis do Brasil!', reacao_erro: 'Alguns pares erraram!', curiosidade: 'Cada época tem seus heróis! Eles arriscaram tudo pelo que acreditavam ser justo e melhor para o país! 🏆' },
          { tipo: 'multipla', pergunta: 'O que foi o Quilombo dos Palmares?', opcoes: ['Uma cidade portuguesa', 'Uma comunidade de escravos fugitivos que viviam livres', 'Uma tribo indígena', 'Um tipo de engenho de açúcar'], correta: 1, reacao_acerto: 'Palmares era uma comunidade de pessoas livres!', reacao_erro: 'Palmares foi uma comunidade de negros fugitivos que viviam livres!', curiosidade: 'O Quilombo dos Palmares existiu por quase 100 anos na serra de Alagoas! Era uma sociedade organizada e autossuficiente com 30.000 habitantes! 🌿' },
          { tipo: 'vf', pergunta: 'O Brasil foi o último país do mundo a abolir a escravidão.', correta: true, reacao_acerto: 'Sim! Em 1888, éramos os últimos!', reacao_erro: 'Era VERDADEIRO! O Brasil foi o último país ocidental a abolir a escravidão.', curiosidade: 'Cuba aboliu em 1886, Brasil em 1888. Éramos os últimos! A luta por igualdade e justiça continua sendo necessária até hoje. ⚖️' },
          { tipo: 'completar', pergunta: 'A data da Proclamação da República do Brasil é 15 de _____ de 1889.', resposta: 'novembro', dica: '(dica: nove _ _ ro)', reacao_acerto: 'Novembro! 15/11/1889!', reacao_erro: 'Era NOVEMBRO! 15 de novembro de 1889.', curiosidade: '15 de novembro é feriado nacional no Brasil! Nesse dia de 1889, o Marechal Deodoro proclamou a república e o Império acabou. 📅' },
          { tipo: 'multipla', pergunta: 'O que eram as "bandeiras" no período colonial?', opcoes: ['Bandeiras para enfeitar as cidades', 'Expedições que exploravam o interior do Brasil', 'Grupos de teatro ambulante', 'Frotas de navios militares'], correta: 1, reacao_acerto: 'Bandeiras eram expedições ao interior!', reacao_erro: 'Bandeiras eram expedições que exploravam o interior do Brasil!', curiosidade: 'Os bandeirantes saíam de São Paulo em longas expedições. Foram eles que descobriram as minas de ouro em Minas Gerais! 🗺️' },
          { tipo: 'ordenar', pergunta: 'Ordene as formas de governo do Brasil do mais antigo ao mais recente:', itens: ['República', 'Colônia Portuguesa', 'Império'], ordemCorreta: [1, 2, 0], reacao_acerto: 'Colônia → Império → República!', reacao_erro: 'A ordem era: Colônia (1500) → Império (1822) → República (1889)!', curiosidade: 'O Brasil passou por 3 grandes fases políticas! Cada uma moldou o país de maneira diferente. A República é nosso atual sistema! 🇧🇷' },
          { tipo: 'lacuna', pergunta: 'Herói nacional:', frase: 'Tiradentes é considerado herói nacional por liderar a _____ Mineira, uma revolta contra os portugueses.', opcoes: ['Independência', 'Inconfidência', 'Proclamação', 'Abolição'], correta: 1, reacao_acerto: 'Inconfidência Mineira!', reacao_erro: 'Era INCONFIDÊNCIA Mineira!', curiosidade: 'A Inconfidência Mineira de 1789 foi uma revolta contra os impostos altos! Tiradentes foi capturado e enforcado. Mas ficou para sempre na memória do Brasil. 🦷' },
          { tipo: 'vf', pergunta: 'Dom João VI veio ao Brasil fugindo de Napoleão Bonaparte.', correta: true, reacao_acerto: 'Sim! Em 1808 a família real chegou ao Rio!', reacao_erro: 'Era VERDADEIRO! A família real portuguesa fugiu de Napoleão para o Brasil em 1808.', curiosidade: 'Em 1808 Napoleão invadiu Portugal e a família real fugiu para o Brasil com 15.000 pessoas! Foi a primeira vez que um rei europeu pisou na América! 👑' },
        ,
          { tipo: 'multipla', pergunta: 'O que foi a Revolução Francesa em 1789?', opcoes: ['Uma guerra contra a Inglaterra', 'Uma revolta do povo contra a monarquia', 'Uma invasão de Napoleão', 'Uma independência de colônia'], correta: 1, reacao_acerto: 'Revolta do povo contra a monarquia!', reacao_erro: 'A Revolução Francesa foi uma revolta do povo que derrubou os reis!', curiosidade: 'A Revolução Francesa criou os ideais de Liberdade, Igualdade e Fraternidade. As cores da bandeira francesa representam esses ideais! 🇫🇷' },
          { tipo: 'vf', pergunta: 'Getúlio Vargas criou as leis trabalhistas (CLT) no Brasil.', correta: true, reacao_acerto: 'Correto! Getúlio criou a CLT em 1943!', reacao_erro: 'Era VERDADEIRO! A CLT, salário mínimo e carteira de trabalho foram criados por Getúlio Vargas!', curiosidade: 'Getúlio Vargas criou o salário mínimo, as férias remuneradas e a carteira de trabalho! Por isso é chamado de "Pai dos Pobres". 📋' },
          { tipo: 'multipla', pergunta: 'Brasília substituiu qual cidade como capital do Brasil?', opcoes: ['São Paulo', 'Salvador', 'Rio de Janeiro', 'Ouro Preto'], correta: 2, reacao_acerto: 'Rio de Janeiro!', reacao_erro: 'Brasília substituiu o RIO DE JANEIRO como capital em 1960!', curiosidade: 'Salvador foi 1ª capital (1549-1763), depois Rio de Janeiro (1763-1960), agora Brasília! JK construiu a nova capital em apenas 3 anos! 🏙️' },
          { tipo: 'completar', pergunta: 'As caravelas foram as embarcações usadas pelos portugueses para navegar durante o século _____.', resposta: 'quinze', dica: '(dica: quin _ e = número XV)', reacao_acerto: 'Século XV (1400s)!', reacao_erro: 'Era o século XV (quinze)! As caravelas navegaram principalmente no século 1400!', curiosidade: 'As caravelas tinham velas triangulares que permitiam navegar contra o vento! Sem elas, Cabral não teria chegado ao Brasil! ⛵' },
          { tipo: 'multipla', pergunta: 'O que foi o Tratado de Tordesilhas (1494)?', opcoes: ['Acordo de paz entre Brasil e Portugal', 'Divisão do mundo entre Portugal e Espanha', 'Abolição da escravidão', 'Declaração de guerra à América'], correta: 1, reacao_acerto: 'Divisão do mundo entre Portugal e Espanha!', reacao_erro: 'Tordesilhas DIVIDIU o mundo entre Portugal e Espanha em 1494!', curiosidade: 'Portugal ficou com Leste (África, Índia, Brasil) e Espanha com o Oeste (resto das Américas). Uma linha imaginária dividiu o planeta! 📜' },
          { tipo: 'vf', pergunta: 'Os Estados Unidos foram o primeiro país das Américas a declarar independência.', correta: true, reacao_acerto: 'Correto! Em 4 de julho de 1776!', reacao_erro: 'Era VERDADEIRO! Os EUA declararam independência em 4 de julho de 1776!', curiosidade: 'A independência americana de 1776 inspirou revoluções no mundo todo, incluindo a Revolução Francesa de 1789 e a Independência do Brasil de 1822! 🗽' },
          { tipo: 'multipla', pergunta: 'O que eram os quilombos no Brasil colonial?', opcoes: ['Portos para embarque de escravos', 'Comunidades de negros fugitivos que viviam livres', 'Fazendas dos colonizadores', 'Tribos indígenas'], correta: 1, reacao_acerto: 'Quilombos eram comunidades de pessoas livres!', reacao_erro: 'Quilombos eram comunidades de negros fugitivos que viviam livres!', curiosidade: 'O Quilombo dos Palmares durou quase 100 anos com 30.000 pessoas livres! Zumbi dos Palmares é símbolo de resistência e liberdade. ✊' },
          { tipo: 'lacuna', pergunta: 'Independência americana:', frase: 'A Declaração de Independência dos EUA foi assinada em _____ de julho de 1776.', opcoes: ['2', '4', '7', '15'], correta: 1, reacao_acerto: '4 de julho!', reacao_erro: 'Era DIA 4 de julho!', curiosidade: 'O 4 de julho é o maior feriado americano! "Independence Day" é celebrado com fogos de artifício em todo o país. 🎆' },
          { tipo: 'vf', pergunta: 'A Inconfidência Mineira de 1789 foi liderada por Tiradentes.', correta: true, reacao_acerto: 'Correto! Tiradentes liderou a revolta!', reacao_erro: 'Era VERDADEIRO! Tiradentes (Joaquim José da Silva Xavier) liderou a Inconfidência!', curiosidade: 'Tiradentes foi o único executado da Inconfidência Mineira. Hoje é feriado nacional em 21 de abril. Seu apelido vem de sua profissão de dentista! 🦷' },
          { tipo: 'multipla', pergunta: 'Qual foi o papel da Princesa Isabel na história do Brasil?', opcoes: ['Declarou a independência', 'Assinou a Lei Áurea abolindo a escravidão', 'Proclamou a República', 'Fundou Brasília'], correta: 1, reacao_acerto: 'A Princesa Isabel assinou a Lei Áurea!', reacao_erro: 'A Princesa Isabel assinou a LEI ÁUREA em 13 de maio de 1888, abolindo a escravidão!', curiosidade: '13 de maio de 1888 — Princesa Isabel assinou a Lei Áurea com canetas diferentes para distribuir como lembrança desse momento histórico! 📜' }
        ]
      },

      /* ── GEOGRAFIA ── */
      geo: {
        niveis: [
          { nome: '⭐ EXPLORADOR', inicio: 0, fala: 'O mundo é enorme e lindo! Vamos explorar!' },
          { nome: '⭐⭐ VIAJANTE', inicio: 5, fala: 'Nível 2! Cada país tem sua história!' },
          { nome: '⭐⭐⭐ CARTÓGRAFO', inicio: 10, fala: 'Nível 3! Você está mapeando o mundo!' },
          { nome: '💎 MESTRE DO GLOBO', inicio: 15, fala: 'NÍVEL MESTRE! Você conhece cada cantinho do mundo!' },
        ],
        perguntas: [
          { tipo: 'multipla', pergunta: 'Quantos estados tem o Brasil?', opcoes: ['23', '25', '26', '27'], correta: 2, reacao_acerto: 'O Brasil tem 26 estados + 1 Distrito Federal!', reacao_erro: 'O Brasil tem 26 estados + o Distrito Federal = 27 unidades federativas!', curiosidade: 'Os 26 estados mais o Distrito Federal (onde fica Brasília) formam nosso país! Cada estado tem sua capital e cultura especial! 🗺️' },
          { tipo: 'vf', pergunta: 'A Amazônia é a maior floresta tropical do mundo.', correta: true, reacao_acerto: 'Sim! A Amazônia é gigante!', reacao_erro: 'Era VERDADEIRO! A Amazônia é a maior floresta tropical!', curiosidade: 'A Amazônia ocupa 60% do território brasileiro e tem mais de 40.000 espécies de plantas! É o pulmão do mundo! 🌳' },
          { tipo: 'multipla', pergunta: 'Qual é a capital do Brasil?', opcoes: ['São Paulo', 'Rio de Janeiro', 'Salvador', 'Brasília'], correta: 3, reacao_acerto: 'Brasília é a capital do Brasil!', reacao_erro: 'Era BRASÍLIA! Inaugurada em 1960.', curiosidade: 'Brasília foi construída do zero em apenas 3 anos! O presidente JK prometeu 50 anos de progresso em 5. Inaugurada em 21 de abril de 1960! 🏙️' },
          { tipo: 'completar', pergunta: 'O maior rio do mundo em volume de água é o _____.', resposta: 'amazonas', dica: '(dica: ama _ _ _ as)', reacao_acerto: 'Rio Amazonas!', reacao_erro: 'Era o RIO AMAZONAS!', curiosidade: 'O Rio Amazonas é tão largo que não dá para ver de uma margem a outra! Lança 20% de toda a água doce dos rios do mundo no oceano! 🌊' },
          { tipo: 'multipla', pergunta: 'Qual é o continente mais populoso do mundo?', opcoes: ['África', 'América', 'Europa', 'Ásia'], correta: 3, reacao_acerto: 'Ásia tem mais de 4,7 bilhões de pessoas!', reacao_erro: 'Era a ÁSIA! Com mais de metade da população mundial.', curiosidade: 'A Ásia tem cerca de 4,7 bilhões de pessoas — mais de 60% da humanidade! China e Índia juntas têm quase 3 bilhões! 🌏' },
          { tipo: 'vf', pergunta: 'O Brasil faz fronteira com todos os países da América do Sul, exceto Chile e Equador.', correta: true, reacao_acerto: 'Correto! Fazemos fronteira com 10 de 12 países!', reacao_erro: 'Era VERDADEIRO! O Brasil não faz fronteira com Chile e Equador.', curiosidade: 'O Brasil é tão grande que faz fronteira com 10 países! Só Chile e Equador ficam de fora. São 16.886 km de fronteiras terrestres! 📍' },
          { tipo: 'multipla', pergunta: 'Qual é o maior país do mundo em área?', opcoes: ['Brasil', 'China', 'Rússia', 'Canadá'], correta: 2, reacao_acerto: 'Rússia é o maior país do mundo!', reacao_erro: 'Era a RÚSSIA! Com 17,1 milhões de km².', curiosidade: 'A Rússia tem 17,1 milhões de km² — quase 2 vezes o Brasil! É tão grande que fuso horário muda 11 vezes atravessando o país! 🌍' },
          { tipo: 'ordenar', pergunta: 'Ordene os continentes do mais populoso ao menos populoso:', itens: ['Europa', 'Ásia', 'América', 'África'], ordemCorreta: [1, 3, 2, 0], reacao_acerto: 'Ásia → África → América → Europa!', reacao_erro: 'A ordem era: Ásia (4,7bi) → África (1,4bi) → América (1bi) → Europa (750mi)!', curiosidade: 'A Ásia tem mais gente que todos os outros continentes juntos! Já a Europa, apesar de muito desenvolvida, tem menos gente que a África! 🌐' },
          { tipo: 'multipla', pergunta: 'Qual bioma cobre grande parte do Nordeste brasileiro?', opcoes: ['Pantanal', 'Caatinga', 'Cerrado', 'Mata Atlântica'], correta: 1, reacao_acerto: 'A Caatinga cobre o sertão nordestino!', reacao_erro: 'Era a CAATINGA! Bioma único do Brasil.', curiosidade: 'A Caatinga existe APENAS no Brasil! É o único bioma exclusivamente brasileiro. Tem espécies únicas como o umbu, a jurema e o xique-xique! 🌵' },
          { tipo: 'vf', pergunta: 'O equador divide a Terra em Hemisfério Norte e Hemisfério Sul.', correta: true, reacao_acerto: 'Correto! O equador é a linha do meio!', reacao_erro: 'Era VERDADEIRO! O equador é a linha imaginária que divide a Terra ao meio.', curiosidade: 'O equador é a linha de 0° de latitude! O Brasil tem parte no hemisfério norte e parte no sul — o equador corta o Pará e o Amapá! 🌐' },
          { tipo: 'associar', pergunta: 'Ligue cada capital ao seu estado:', pares: [{ esq: 'São Paulo', dir: 'SP' }, { esq: 'Belo Horizonte', dir: 'MG' }, { esq: 'Salvador', dir: 'BA' }, { esq: 'Fortaleza', dir: 'CE' }], reacao_acerto: 'Você conhece as capitais brasileiras!', reacao_erro: 'Alguns pares estavam errados!', curiosidade: 'Cada estado brasileiro tem uma capital! Algumas têm o mesmo nome do estado, como São Paulo, Rio de Janeiro, Mato Grosso e Pará! 🏙️' },
          { tipo: 'multipla', pergunta: 'Qual é o maior estado do Brasil em área?', opcoes: ['Mato Grosso', 'Pará', 'Amazonas', 'Minas Gerais'], correta: 2, reacao_acerto: 'Amazonas é o maior estado brasileiro!', reacao_erro: 'Era o AMAZONAS! Com 1,57 milhão de km².', curiosidade: 'O Amazonas é tão grande que cabem 15 estados de São Paulo dentro dele! A capital Manaus fica no meio da selva amazônica! 🌿' },
          { tipo: 'lacuna', pergunta: 'Capitais do mundo:', frase: 'A capital da Argentina, país vizinho do Brasil, é _____ .', opcoes: ['Lima', 'Montevidéu', 'Buenos Aires', 'Santiago'], correta: 2, reacao_acerto: 'Buenos Aires! Correto!', reacao_erro: 'Era BUENOS AIRES!', curiosidade: 'Buenos Aires significa "bons ares" em espanhol! É uma das maiores cidades da América Latina com cerca de 15 milhões na Grande Buenos Aires! 🇦🇷' },
          { tipo: 'vf', pergunta: 'A Antártida é o continente mais frio do mundo.', correta: true, reacao_acerto: 'Sim! A temperatura pode chegar a -89°C!', reacao_erro: 'Era VERDADEIRO! A Antártida registrou -89,2°C!', curiosidade: 'A Antártida é coberta por uma camada de gelo de até 4km de espessura! Se todo o gelo derreter, o nível dos oceanos sobe 60 metros! 🧊' },
          { tipo: 'completar', pergunta: 'O Brasil pertence ao continente chamado _____.', resposta: 'america', dica: '(dica: amé _ _ _ a)', reacao_acerto: 'América! Correto!', reacao_erro: 'Era AMÉRICA!', curiosidade: 'O Brasil está na América do Sul. O continente americano vai do Alasca (norte) até a Terra do Fogo na Argentina (sul)! 🌎' },
          { tipo: 'multipla', pergunta: 'Qual oceano banha as praias do Brasil?', opcoes: ['Oceano Índico', 'Oceano Pacífico', 'Oceano Atlântico', 'Mar Mediterrâneo'], correta: 2, reacao_acerto: 'Oceano Atlântico!', reacao_erro: 'Era o OCEANO ATLÂNTICO! Com 7.500 km de costa.', curiosidade: 'O Brasil tem a 16ª maior costa do mundo com 7.491 km de praias! Vai do Oiapoque no Amapá ao Chuí no Rio Grande do Sul! 🏖️' },
          { tipo: 'ordenar', pergunta: 'Ordene as regiões do Brasil de Norte a Sul:', itens: ['Sudeste', 'Norte', 'Sul', 'Nordeste'], ordemCorreta: [1, 3, 0, 2], reacao_acerto: 'Norte → Nordeste → Sudeste → Sul!', reacao_erro: 'A ordem era: Norte → Nordeste → Sudeste → Sul!', curiosidade: 'O Brasil tem 5 regiões: Norte, Nordeste, Centro-Oeste, Sudeste e Sul! Cada uma tem climas, culturas e sotaques únicos! 🗺️' },
          { tipo: 'lacuna', pergunta: 'Pontos cardeais:', frase: 'O Sol nasce no _____ e se põe no Oeste.', opcoes: ['Norte', 'Sul', 'Leste', 'Centro'], correta: 2, reacao_acerto: 'Leste (ou Este)! O Sol sempre nasce no Leste!', reacao_erro: 'Era LESTE! O Sol nasce no Leste e se põe no Oeste.', curiosidade: 'Os 4 pontos cardeais são: Norte (N), Sul (S), Leste (L) e Oeste (O)! Uma dica: Norte, Sul, Leste e Oeste = "Nunca Saio Longe de Ouro"! 🧭' },
          { tipo: 'vf', pergunta: 'A África é o continente com mais países do mundo.', correta: true, reacao_acerto: 'Sim! A África tem 54 países!', reacao_erro: 'Era VERDADEIRO! A África tem 54 países reconhecidos!', curiosidade: 'A África tem 54 países e mais de 2.000 línguas diferentes! É o berço da humanidade — os primeiros humanos evoluíram lá há 200.000 anos! 🌍' },
          { tipo: 'multipla', pergunta: 'Qual é a maior cidade do Brasil?', opcoes: ['Rio de Janeiro', 'Brasília', 'Belo Horizonte', 'São Paulo'], correta: 3, reacao_acerto: 'São Paulo é a maior cidade brasileira!', reacao_erro: 'Era SÃO PAULO! Com mais de 12 milhões de habitantes.', curiosidade: 'São Paulo tem mais de 12 milhões de moradores e é a maior cidade da América do Sul! A Grande São Paulo tem mais de 20 milhões! 🏙️' },
        ,
          { tipo: 'multipla', pergunta: 'Qual é o maior oceano do mundo?', opcoes: ['Oceano Atlântico', 'Oceano Índico', 'Oceano Pacífico', 'Oceano Ártico'], correta: 2, reacao_acerto: 'Oceano Pacífico é o maior!', reacao_erro: 'O OCEANO PACÍFICO é o maior! Cobre 1/3 do planeta!', curiosidade: 'O Pacífico é tão grande que todos os continentes caberiam dentro dele! Magalhães o chamou de "mar pacífico" pois estava calmo quando o atravessou! 🌊' },
          { tipo: 'vf', pergunta: 'O Deserto do Saara é o maior deserto quente do mundo.', correta: true, reacao_acerto: 'Sim! O Saara é o maior deserto quente!', reacao_erro: 'Era VERDADEIRO! O Saara é o maior deserto quente (9,2 milhões km²)!', curiosidade: 'O Saara é maior que o Brasil! Mas o MAIOR deserto do mundo é a Antártida (fria). Desertos são lugares com menos de 250mm de chuva por ano! 🏜️' },
          { tipo: 'multipla', pergunta: 'Quais são as capitais dos 3 estados do Sul do Brasil?', opcoes: ['Salvador, Recife e Fortaleza', 'Curitiba, Florianópolis e Porto Alegre', 'São Paulo, Rio e BH', 'Manaus, Belém e Macapá'], correta: 1, reacao_acerto: 'Curitiba (PR), Florianópolis (SC) e Porto Alegre (RS)!', reacao_erro: 'As capitais do Sul são Curitiba, Florianópolis e Porto Alegre!', curiosidade: 'O Sul tem forte influência europeia de alemães e italianos que imigraram no século XIX! Por isso Blumenau tem um Oktoberfest brasileiro! 🌲' },
          { tipo: 'completar', pergunta: 'A cidade mais populosa do mundo é _____ (Japão).', resposta: 'tóquio', dica: '(dica: tó _ _ io)', reacao_acerto: 'Tóquio!', reacao_erro: 'Era TÓQUIO!', curiosidade: 'A Grande Tóquio tem 37 milhões de habitantes — mais que o Canadá inteiro! É a maior aglomeração urbana do planeta! 🗾' },
          { tipo: 'vf', pergunta: 'O Rio Nilo é o maior rio do mundo em extensão.', correta: true, reacao_acerto: 'Correto! O Nilo tem ~6.650 km!', reacao_erro: 'Era VERDADEIRO! O Nilo (6.650km) é o mais longo, mas o Amazonas tem mais volume!', curiosidade: 'O Nilo é o mais longo, mas o Amazonas despeja 5x mais água no oceano! Comprimento vs. volume são recordes diferentes! 🌊' },
          { tipo: 'multipla', pergunta: 'Como se chama a linha imaginária que divide Hemisfério Norte e Sul?', opcoes: ['Trópico de Capricórnio', 'Meridiano de Greenwich', 'Equador', 'Trópico de Câncer'], correta: 2, reacao_acerto: 'O Equador divide os hemisférios!', reacao_erro: 'O EQUADOR é a linha que divide Norte e Sul!', curiosidade: 'No Equador, o dia e a noite têm quase sempre 12 horas cada. Não há estações bem definidas. O Brasil tem parte em ambos os hemisférios! 🌍' },
          { tipo: 'multipla', pergunta: 'Qual bioma brasileiro é chamado de "berço das águas"?', opcoes: ['Pantanal', 'Caatinga', 'Cerrado', 'Pampa'], correta: 2, reacao_acerto: 'Cerrado — onde nascem os grandes rios!', reacao_erro: 'Era CERRADO! De lá nascem o Araguaia, Tocantins, São Francisco!', curiosidade: 'O Cerrado é onde nascem os principais rios do Brasil! Se desaparecer, afeta o abastecimento de água de metade do país. 💧' },
          { tipo: 'vf', pergunta: 'A Índia é atualmente o país mais populoso do mundo (2024).', correta: true, reacao_acerto: 'Correto! A Índia ultrapassou a China em 2023!', reacao_erro: 'Era VERDADEIRO! Em 2023, a ÍNDIA ultrapassou a China!', curiosidade: 'Em 2023, a Índia com 1,43 bilhão ultrapassou a China com 1,41 bilhão! O mundo tem 8 bilhões de pessoas no total! 🌏' },
          { tipo: 'lacuna', pergunta: 'Pontos cardeais:', frase: 'Os 4 pontos cardeais são Norte, Sul, _____ e Oeste.', opcoes: ['Centro', 'Leste', 'Alto', 'Profundo'], correta: 1, reacao_acerto: 'Leste (ou Este)!', reacao_erro: 'Era LESTE! Norte, Sul, Leste e Oeste são os pontos cardeais.', curiosidade: 'Mnemônico para os pontos cardeais: "Nunca Saio Longe de Ouro" = Norte, Sul, Leste (=Oriente), Oeste! 🧭' },
          { tipo: 'multipla', pergunta: 'Qual é o menor país do mundo?', opcoes: ['Luxemburgo', 'Mônaco', 'Vaticano', 'San Marino'], correta: 2, reacao_acerto: 'Vaticano é o menor país!', reacao_erro: 'O VATICANO é o menor país do mundo, com apenas 0,44 km²!', curiosidade: 'O Vaticano cabe 16 vezes dentro do Parque Ibirapuera em SP! É um Estado independente dentro de Roma com cerca de 800 habitantes! ⛪' }
        ]
      },

      /* ── ARTES ── */
      artes: {
        niveis: [
          { nome: '⭐ ARTISTA INICIANTE', inicio: 0, fala: 'Arte é expressão da alma! Vamos criar!' },
          { nome: '⭐⭐ PINTOR MIRIM', inicio: 5, fala: 'Nível 2! Cores e formas têm muito a dizer!' },
          { nome: '⭐⭐⭐ MÚSICO', inicio: 10, fala: 'Nível 3! A arte está em todo lugar!' },
          { nome: '💎 ARTISTA MESTRE', inicio: 15, fala: 'NÍVEL MESTRE! Você é um artista completo!' },
        ],
        perguntas: [
          { tipo: 'multipla', pergunta: 'Quais são as cores primárias?', opcoes: ['Verde, laranja e roxo', 'Vermelho, azul e amarelo', 'Rosa, branco e preto', 'Ciano, magenta e vermelho'], correta: 1, reacao_acerto: 'Vermelho, azul e amarelo são as cores primárias!', reacao_erro: 'As cores PRIMÁRIAS são: Vermelho, Azul e Amarelo!', curiosidade: 'Cores primárias não podem ser criadas misturando outras. De vermelho+azul+amarelo surgem TODAS as outras cores! Tente misturar! 🎨' },
          { tipo: 'vf', pergunta: 'Vermelho + Azul = Roxo/Violeta.', correta: true, reacao_acerto: 'Sim! Vermelho e azul formam roxo!', reacao_erro: 'Era VERDADEIRO! Vermelho + Azul = Roxo!', curiosidade: 'Misturando as cores primárias duas a duas formamos as secundárias: Vermelho+Azul=Roxo, Azul+Amarelo=Verde, Vermelho+Amarelo=Laranja! 🔴🔵' },
          { tipo: 'multipla', pergunta: 'Qual instrumento pertence à família das cordas?', opcoes: ['Flauta', 'Violino', 'Tambor', 'Trompete'], correta: 1, reacao_acerto: 'Violino é de cordas!', reacao_erro: 'Era o VIOLINO! As cordas vibram para produzir som.', curiosidade: 'Instrumentos de corda produzem som quando as cordas vibram! Violino, viola, cello, guitarra, violão, harpa — todos são de corda! 🎻' },
          { tipo: 'completar', pergunta: 'O pai do carnaval brasileiro, que compôs "Aquarela do Brasil" foi Ary _____.', resposta: 'barroso', dica: '(dica: bar _ _ so)', reacao_acerto: 'Ary Barroso!', reacao_erro: 'Era ARY BARROSO!', curiosidade: 'Ary Barroso compôs "Aquarela do Brasil" em 1939! É considerada a música mais internacional do Brasil, tocada em filmes de Hollywood! 🎵' },
          { tipo: 'vf', pergunta: 'A Mona Lisa foi pintada por Leonardo da Vinci.', correta: true, reacao_acerto: 'Sim! Da Vinci pintou entre 1503-1519!', reacao_erro: 'Era VERDADEIRO! A Mona Lisa é de Leonardo da Vinci!', curiosidade: 'A Mona Lisa fica no Museu do Louvre em Paris e é visitada por 9 milhões de pessoas por ano! Seu sorriso misterioso fascina o mundo! 🖼️' },
          { tipo: 'multipla', pergunta: 'O que é escultura?', opcoes: ['Uma pintura em tela', 'Uma obra de arte tridimensional feita em materiais sólidos', 'Um tipo de música', 'Uma técnica de desenho'], correta: 1, reacao_acerto: 'Escultura é arte 3D em materiais sólidos!', reacao_erro: 'Escultura é arte tridimensional (tem largura, altura e profundidade)!', curiosidade: 'Esculturas podem ser feitas em pedra, madeira, bronze, argila, gesso... O Cristo Redentor no Rio é uma das mais famosas do mundo! 🗿' },
          { tipo: 'ordenar', pergunta: 'Ordene as notas musicais:', itens: ['Mi', 'Dó', 'Sol', 'Ré'], ordemCorreta: [1, 3, 0, 2], reacao_acerto: 'Dó, Ré, Mi, Sol — você sabe música!', reacao_erro: 'A ordem era: Dó, Ré, Mi, Sol!', curiosidade: 'A escala musical tem 7 notas: Dó, Ré, Mi, Fá, Sol, Lá, Si! A frase "Dó de leite, Ré de rua, Mi de mim..." ajuda a lembrar! 🎵' },
          { tipo: 'multipla', pergunta: 'Tarsila do Amaral foi uma importante artista de qual movimento?', opcoes: ['Barroco', 'Renascimento', 'Modernismo Brasileiro', 'Impressionismo'], correta: 2, reacao_acerto: 'Tarsila foi ícone do Modernismo Brasileiro!', reacao_erro: 'Tarsila do Amaral é do MODERNISMO BRASILEIRO!', curiosidade: 'Tarsila pintou "Abaporu" em 1928 para o marido Oswald de Andrade. Em 1995 foi vendida por 1,4 milhão de dólares! Uma das obras mais caras do Brasil! 🎨' },
          { tipo: 'vf', pergunta: 'O samba é um ritmo musical de origem africana.', correta: true, reacao_acerto: 'Sim! O samba veio das tradições africanas!', reacao_erro: 'Era VERDADEIRO! O samba tem raízes africanas.', curiosidade: 'O samba surgiu no final do século XIX no Rio de Janeiro, criado por descendentes de africanos. Em 2016 foi declarado Patrimônio Cultural Imaterial pela UNESCO! 🎶' },
          { tipo: 'multipla', pergunta: 'Qual a diferença entre escultura e pintura?', opcoes: ['Escultura usa tinta e pintura usa argila', 'Escultura é 3D, pintura é 2D', 'Não há diferença', 'Escultura é mais moderna'], correta: 1, reacao_acerto: 'Escultura tem 3 dimensões, pintura tem 2!', reacao_erro: 'Escultura é tridimensional (3D), pintura é bidimensional (2D)!', curiosidade: 'Uma tela tem altura e largura (2D). Uma escultura tem altura, largura E profundidade (3D). Por isso você pode andar ao redor de uma escultura! 🖼️' },
          { tipo: 'lacuna', pergunta: 'Instrumentos de sopro:', frase: 'A _____ é um instrumento de sopro feito de bambu muito usado na música folclórica.', opcoes: ['Viola', 'Zabumba', 'Flauta', 'Berimbau'], correta: 2, reacao_acerto: 'Flauta! Correto!', reacao_erro: 'Era FLAUTA!', curiosidade: 'Flautas feitas de bambu e osso foram encontradas com mais de 40.000 anos! São os instrumentos musicais mais antigos conhecidos! 🎵' },
          { tipo: 'associar', pergunta: 'Ligue o instrumento à sua família:', pares: [{ esq: '🥁 Tambor', dir: 'Percussão' }, { esq: '🎻 Violino', dir: 'Cordas' }, { esq: '🎺 Trompete', dir: 'Sopro metal' }, { esq: '🎹 Piano', dir: 'Teclas/percussão' }], reacao_acerto: 'Você conhece as famílias dos instrumentos!', reacao_erro: 'Alguns pares erraram!', curiosidade: 'O piano é especial porque bate cordas com martelinhos — é percussão E corda ao mesmo tempo! Por isso é difícil classificar! 🎹' },
          { tipo: 'multipla', pergunta: 'O que é uma obra de arte abstrata?', opcoes: ['Obra que copia a realidade', 'Obra que usa formas e cores sem representar coisas reais', 'Obra feita de pedra', 'Obra que usa apenas preto e branco'], correta: 1, reacao_acerto: 'Arte abstrata usa formas sem representar objetos reais!', reacao_erro: 'Arte abstrata usa formas e cores sem copiar a realidade!', curiosidade: 'Kandinsky foi um dos primeiros artistas abstratos! Ele acreditava que as cores e formas podiam transmitir emoções sem precisar mostrar coisas reais! 🌈' },
          { tipo: 'vf', pergunta: 'O forró é um ritmo musical típico do Nordeste brasileiro.', correta: true, reacao_acerto: 'Sim! O forró nasceu no Nordeste!', reacao_erro: 'Era VERDADEIRO! O forró é nordestino!', curiosidade: 'Luiz Gonzaga, o "Rei do Baião", popularizou o forró no Brasil! Toque, zabumba e triângulo são os instrumentos básicos! ⬆️' },
          { tipo: 'completar', pergunta: 'A arte de modelar figuras com argila se chama _____.', resposta: 'cerâmica', dica: '(dica: cerâ _ _ _ a)', reacao_acerto: 'Cerâmica! Correto!', reacao_erro: 'Era CERÂMICA!', curiosidade: 'A cerâmica tem mais de 25.000 anos! Os antigos faziam potes, vasos e figuras de argila que endureciam com o fogo. Ainda fazemos isso hoje! 🏺' },
          { tipo: 'multipla', pergunta: 'Qual a cor que se forma quando misturamos azul e amarelo?', opcoes: ['Roxo', 'Laranja', 'Verde', 'Marrom'], correta: 2, reacao_acerto: 'Azul + Amarelo = Verde!', reacao_erro: 'Era VERDE! Azul e amarelo formam verde.', curiosidade: 'Misturando as 3 primárias em partes iguais, você obtém marrom ou preto. Mas misturando 2 a 2 você obtém as secundárias! 🎨' },
          { tipo: 'ordenar', pergunta: 'Ordene as cores do arco-íris (vermelho ao violeta):', itens: ['Verde', 'Vermelho', 'Amarelo', 'Azul'], ordemCorreta: [1, 2, 0, 3], reacao_acerto: 'Vermelho, Amarelo, Verde, Azul — parte do arco-íris!', reacao_erro: 'No arco-íris: Vermelho → Laranja → Amarelo → Verde → Azul → Índigo → Violeta!', curiosidade: 'A mnemônica para as cores do arco-íris: Vermelho, Laranja, Amarelo, Verde, Azul, Índigo, Violeta = VOLAGAV! 🌈' },
          { tipo: 'vf', pergunta: 'A capoeira é uma luta-dança criada pelos escravizados africanos no Brasil.', correta: true, reacao_acerto: 'Sim! A capoeira une luta, dança e música!', reacao_erro: 'Era VERDADEIRO! A capoeira foi criada por africanos escravizados no Brasil.', curiosidade: 'A capoeira disfarçava a luta como dança para enganar os senhores! Em 2014 a UNESCO reconheceu a capoeira como Patrimônio Cultural Imaterial da Humanidade! 🥋' },
          { tipo: 'multipla', pergunta: 'O que é um autorretrato?', opcoes: ['Retrato de uma paisagem', 'Retrato de outra pessoa', 'Retrato que o artista faz de si mesmo', 'Um tipo de fotografia'], correta: 2, reacao_acerto: 'Autorretrato é quando o artista se pinta!', reacao_erro: 'Autorretrato é o retrato que o artista faz de si mesmo!', curiosidade: 'Van Gogh pintou mais de 30 autorretratos! Frida Kahlo também é famosa pelos seus. Selfie é o autorretrato digital moderno! 🤳' },
          { tipo: 'lacuna', pergunta: 'Patrimônio cultural:', frase: 'O _____ é uma dança folclórica nordestina que mistura elementos indígenas, africanos e europeus.', opcoes: ['Samba', 'Forró', 'Maracatu', 'Bumba Meu Boi'], correta: 3, reacao_acerto: 'Bumba Meu Boi! Riqueza cultural nordestina!', reacao_erro: 'Era BUMBA MEU BOI!', curiosidade: 'O Bumba Meu Boi é uma das festas mais ricas do Brasil! Combina música, dança e teatro numa história de morte e ressurreição de um boi! 🐂' },
        ,
          { tipo: 'multipla', pergunta: 'Quem pintou o teto da Capela Sistina?', opcoes: ['Leonardo da Vinci', 'Rafael', 'Michelangelo', 'Caravaggio'], correta: 2, reacao_acerto: 'Michelangelo pintou a Sistina!', reacao_erro: 'MICHELANGELO pintou o teto da Sistina (1508-1512)!', curiosidade: 'Michelangelo levou 4 anos deitado num andaime para pintar o teto! "A Criação de Adão" é a cena mais famosa. 🎨' },
          { tipo: 'vf', pergunta: 'O jazz é um estilo musical originário dos Estados Unidos.', correta: true, reacao_acerto: 'Sim! Jazz nasceu em Nova Orleans!', reacao_erro: 'Era VERDADEIRO! O jazz surgiu em Nova Orleans com influências africanas e europeias!', curiosidade: 'O jazz influenciou toda a música moderna! No Brasil deu origem à bossa nova com Tom Jobim e João Gilberto! 🎷' },
          { tipo: 'multipla', pergunta: 'O que é uma partitura?', opcoes: ['Um tipo de instrumento', 'A escrita musical com notas e símbolos', 'Uma dança típica', 'Um tipo de pintura'], correta: 1, reacao_acerto: 'Partitura é a escrita da música!', reacao_erro: 'Partitura é o papel com as notas musicais escritas!', curiosidade: 'A partitura é como o "texto" da música! Beethoven escreveu partituras mesmo quando ficou completamente surdo! 🎵' },
          { tipo: 'vf', pergunta: 'Vincent van Gogh vendeu muitos quadros e ficou rico em vida.', correta: false, reacao_acerto: 'Correto! Van Gogh só era famoso após morrer!', reacao_erro: 'Era FALSO! Van Gogh vendeu apenas um quadro em vida! Só ficou famoso após sua morte.', curiosidade: 'Van Gogh vendeu apenas 1 quadro em vida! Hoje "Noite Estrelada" vale centenas de milhões! O reconhecimento em arte pode levar décadas! 🌟' },
          { tipo: 'multipla', pergunta: 'Qual estilo musical é símbolo cultural do Rio de Janeiro?', opcoes: ['Forró', 'Samba e Bossa Nova', 'Axé', 'Baião'], correta: 1, reacao_acerto: 'Samba e Bossa Nova!', reacao_erro: 'O SAMBA e a BOSSA NOVA são marcas culturais do Rio!', curiosidade: 'Tom Jobim e Vinicius de Moraes criaram "A Garota de Ipanema" no Bar Veloso no Rio! É uma das músicas mais gravadas do mundo! 🎶' },
          { tipo: 'multipla', pergunta: 'O que é o impressionismo?', opcoes: ['Arte medieval religiosa', 'Estilo que captura impressões rápidas de luz e cor', 'Escultura abstrata', 'Arte geométrica moderna'], correta: 1, reacao_acerto: 'Impressionismo captura luz e cor!', reacao_erro: 'Impressionismo tenta capturar as impressões visuais da luz e cor!', curiosidade: 'Claude Monet pintou a mesma catedral de Rouen 30 vezes em horas diferentes do dia para ver como a luz mudava! ☀️' },
          { tipo: 'multipla', pergunta: 'Arte rupestre são?', opcoes: ['Esculturas gregas', 'Pinturas em rochas feitas por humanos primitivos', 'Objetos de jade chineses', 'Instrumentos africanos'], correta: 1, reacao_acerto: 'Arte rupestre: pinturas em rochas!', reacao_erro: 'Arte rupestre são pinturas em pedras por humanos pré-históricos!', curiosidade: 'No Parque de Serra da Capivara (PI), há arte rupestre com 25.000 anos! Registros da vida dos primeiros brasileiros! 🪨' },
          { tipo: 'lacuna', pergunta: 'Ritmo nordestino:', frase: 'O _____ é um ritmo musical nordestino tocado com triângulo, zabumba e sanfona.', opcoes: ['Samba', 'Axé', 'Forró', 'Baião'], correta: 2, reacao_acerto: 'Forró!', reacao_erro: 'Era FORRÓ!', curiosidade: 'O Forró ganhou o mundo! Luiz Gonzaga é o "Rei do Baião" que globalizou essa música nordestina. Hoje é popular na Europa! 🎶' },
          { tipo: 'vf', pergunta: 'A capoeira é simultaneamente uma luta, dança e expressão cultural.', correta: true, reacao_acerto: 'Sim! Capoeira une luta, dança e música!', reacao_erro: 'Era VERDADEIRO! Capoeira mistura luta, dança, música e filosofia!', curiosidade: 'A capoeira foi criada por africanos escravizados disfarçando a luta como dança! Em 2014 a UNESCO reconheceu como Patrimônio da Humanidade! 🥋' },
          { tipo: 'multipla', pergunta: 'O que é um autorretrato?', opcoes: ['Retrato de uma paisagem', 'Retrato de outra pessoa', 'Retrato que o artista faz de si mesmo', 'Fotografia de grupo'], correta: 2, reacao_acerto: 'Autorretrato é o artista se pintando!', reacao_erro: 'Autorretrato é o ARTISTA pintando a si mesmo!', curiosidade: 'Van Gogh pintou mais de 30 autorretratos! Frida Kahlo também é famosa pelos seus. A selfie é o autorretrato digital moderno! 🤳' }
        ]
      },
    };